### PR TITLE
Add hot reload saylinks as well as a rule to determine if you bypass the saylinks.

### PR DESCRIPTION
**Pull request by KinglyKrab**

### CODE REVIEW

**Comment by Akkadius** [comment]
This is missing the hot reload bits and duplicates functionality that is already covered by `SendEmoteMessageRaw` 

`SendEmoteMessageRaw` can send with a minimum account status which can cover the messages needed in the hot reload functionality

**Comment by KinglyKrab** [comment]
SendStatusMessage allows a min/max status, not just minimum status, while not necessarily 100% useful here, it is useful elsewhere in the future more than likely.

**Comment by Akkadius** [comment]
Yeah I see the difference; but I've never seen a use case where we need to set a "max status" for a message or anything; we'd be better off just removing the duplicated message logic

**Comment by Akkadius** [comment]
Nice work!

**Pull request merged**
