### PR TITLE
Fix zone startup crash if maps not installed

### PR DESCRIPTION
**Pull request by hgtw**
Just a minor inconvenience when developing without maps installed, shouldn't affect normal servers

### CODE REVIEW

**Comment by Akkadius** [comment]
Curious why you wouldn’t just have maps?

**Review by KinglyKrab — APPROVED** [review]
Looks good to me, fixing crashes that only affect a few is still fixing a crash. Not sure how many would encounter not having maps, but a worthwhile fix nonetheless. Good work. 👍

**Comment by mackal** [comment]
We shouldn't crash. But wouldn't it be better to just fail to load if we have no map file? Shit doesn't work very well without them :P

**Comment by hgtw** [comment]
While working on expeditions I spread development with another computer and laptop rather than the vm I usually used and cloning the map repo on all of them wasn't necessary for what I was doing. It doesn't crash every zone so I only ran into it later when zoning around to start documenting a usage example and update quests.

Someone in discord a few months ago had these crashes when they had maps installed in old/wrong paths so it fixes that edge case too.

**Pull request merged**
