### PR TITLE
Light wield for Npcs/mobs

### PR DESCRIPTION
**Pull request by noudess**
NPC/Mobs do seem to be willing to equip light sources that are primary/secondary when traded or as loot.  Made the change.

### CODE REVIEW

**Comment by mackal** [comment]
Does this end affect combat at all?

**Comment by noudess** [comment]
I guess only in that if you give a pet a light item and he has a primary/secondary slot open, it will use it for light.

**Comment by mackal** [comment]
It's not gonna like enable dual wield on NPCs if you give them two of them?

**Comment by noudess** [comment]
I'll test that.  Great catch.

**Comment by noudess** [comment]
Yes, you were correct.  They don't check for weapon in attack code for offhand, they just check for a texture, then specifically cancel the attack if is a shield.  I fixed it so it rejects any non 1handed weapon.

**Pull request merged**
