### PR TITLE
[Bug Fix] Handle memory leaks from return value of Client::GetTraderItems()

### PR DESCRIPTION
**Pull request by Quintinon**

### CODE REVIEW

**Comment by hgtw** [comment]
This one looks like a duplicate of the changes in 2265 and one of the changes from 2262

**Comment by Quintinon** [comment]
> This one looks like a duplicate of the changes in #2265 and one of the changes from #2262

I'll audit the branches for duplicates. I tried to not have duplicates but seems like I missed some. Thanks for the feedback!

**Comment by Quintinon** [comment]
Confirmed that PR #2265 was superseded by this one. I think I messed up my branches, I abandoned that other PR in favor of this one.
I'm unsure how to remove the duplicate change from #2262 without redoing the entire PR. If that is what is desired I can do it though.

**Review by hgtw — APPROVED** [review]

**Comment by Quintinon** [comment]
Other branch has the duplicate change removed.

**Review by Akkadius — APPROVED** [review]

**Pull request merged**
