### PR TITLE
[Bug Fix] Fix Bot/Character ID Overlap in Groups

### PR DESCRIPTION
**Pull request by Kinglykrab**
# Notes
- Attempt to fix bot/character ID overlap in groups keeping bots with the same unique identifier as players from not spawning on zone.
- Adds `bot_id` to `group_id` to differentiate bots from characters and hopefully alleviate this issue.

### CODE REVIEW

**Comment by Akkadius** [comment]
This is going to need some thorough testing done

**Comment by Kinglykrab** [comment]
> This is going to need some thorough testing done

Yeah, I’d like if Karana could test it as well as Lancelot Jim.

**Comment by neckkola** [comment]
Good afternoon @Kinglykrab.  I ran some tests and did not have any problems zoning in a group with a bot that shared the id of the character.  My test was a player(44) and two bots; bot1(44) bot(46).  

I did notice that I was not able to invite another players' bot.  I could send the group invite, but they never joined the group.  Not sure if that is intended or not.  The other player shared a its id with the bot(1).

I also tested within a raid.  No issue.  Once in the raid, I moved the other player and their bots to the same group, worked fine.  Zoned, no issues anywhere.

**Comment by Kinglykrab** [comment]
> Good afternoon @Kinglykrab. I ran some tests and did not have any problems zoning in a group with a bot that shared the id of the character. My test was a player(44) and two bots; bot1(44) bot(46).
> 
> I did notice that I was not able to invite another players' bot. I could send the group invite, but they never joined the group. Not sure if that is intended or not. The other player shared a its id with the bot(1).
> 
> I also tested within a raid. No issue. Once in the raid, I moved the other player and their bots to the same group, worked fine. Zoned, no issues anywhere.

Hmmm, I didn't try inviting another player's bots, but I think you have to invite the owner.

**Comment by neckkola** [comment]
I tried both single and with the owner already in the group.  Same result, no dice.

**Comment by Akkadius** [comment]
What's the status on this?

**Comment by Kinglykrab** [comment]
> What's the status on this?

Just need to wait on other stuff to be merged so this can be rebased without rebasing it multiple times.

I've tested it on my end and it seems to resolve the issue.

**Review by Akkadius — APPROVED** [review]

**Comment by MortimerGreenwald** [comment]
Has anyone tested bot creation on this PR? Not sure if it's related or not but we're getting a "Failed to query name availability" with this.

**Pull request merged**
