### PR TITLE
[Spells] Bard Dot Pulse Resist Fix

### PR DESCRIPTION
**Pull request by RoT-PvP**
Previously, if a bard landed the initial "cast" of their bard song the pulses afterward would not have a resist check. There is likely a better way to write this but this is what worked for me so far.

### CODE REVIEW

**Comment by mackal** [comment]
This whole pulse "optimization" is just bad and needs to be removed. It causes more problems than it's worth.

**Comment by splose** [comment]
> This whole pulse "optimization" is just bad and needs to be removed. It causes more problems than it's worth.

This is how we give feedback to new people who are obviously trying to learn now? 

Your comment is bad and the opposite of helping. **_Instead of the snarky quotes maybe tell him why its bad, and why "it causes more problems than it's worth."_** Do you feel better sitting there with an IT degree and years of EQEmu experience telling this guy who has been coding for like 2-3 months his code is bad?

When do you realize that putting up PRs is extra work for server operators? Then on top of that having to deal with nonsense like this is a pretty common reason people cite for not contributing and hoarding their code. You do this the most and to anyone who is not in your little clique and whenever anyone tells you where to go after they seem like the bad guy. 

We should be encouraging new people like this and making them want to contribute. The future of the community depends on it. Do better.

**Comment by Akkadius** [comment]
Need folks more versed on intended functionality to give their thoughts on this

**Comment by mackal** [comment]
We can probably call `IsDetrimentalSpell()` only once. It also appears that the resist check is done in `Mob::SpellOnTarget()`. So it's probably better to just come with with a better check to skip the optimization and just call `SpellOnTarget()` without the resist override to get the full behavior.

**Comment by RoT-PvP** [comment]
May have found a bug with this that causes a crash. If a bard is running a song on a mob and then it is charmed by someone he cannot attack the reapplication may cause a crash. Need to verify this.

**Comment by Akkadius** [comment]
Closing this until there is more of a clear path forward on this one

**Pull request closed without merging**
