### PR TITLE
[Bug Fix] Bug fix for raid mark NPC across zones

### PR DESCRIPTION
**Pull request by neckkola**
A bug was discovered with the raid mark npc functionality.

Issue: When an NPC is marked and a raid member zones to a zone that has a mob with the same entity_id, it would be inadvertently marked.

Fix: Updated the pattern to use the entity_id, zone_id, and instance_id for the marked_npc to ensure correctness.  Updated raid object attributes and database structure to accommodate.

Thanks.

### CODE REVIEW

**Comment by neckkola** [comment]
Sorry for the history.  Forgot to clean that.  :-(

**Comment by Kinglykrab** [comment]
Merge conflicts.

**Comment by Akkadius** [comment]
I really appreciate the cleverness of this solution, however instead of overloading the one field just expand it into individual columns in the table it's not going to hurt anything.

```
marked_npc_1
marked_npc_1_zone_id
marked_npc_1_instance_id
marked_npc_2
marked_npc_2_zone_id
marked_npc_2_instance_id
marked_npc_3
marked_npc_3_zone_id
marked_npc_3_instance_id
```

**Comment by neckkola** [comment]
Thanks Akk.  I will update accordingly and I did think it was clever.  :-)

**Review by Akkadius — APPROVED** [review]

**Pull request merged**
