### PR TITLE
Added Rule to enable AA Ding()

### PR DESCRIPTION
**Pull request by noudess**
Added rule to allow for a DING() sound when an AA point is earned.  This will allow low xp/classic like servers where AA dings are still a major event to play the sound when the AA is earned.  Default is off to remain as code is currently written.

### CODE REVIEW

**Comment by joligario** [comment]
Since you are adding this, you may want to add ability to customize 3 options: Silent (Default), Ding, Fanfare.

**Comment by noudess** [comment]
> Since you are adding this, you may want to add ability to customize 3 options: Silent (Default), Ding, Fanfare.

How do I code Fanfare?

**Comment by joligario** [comment]
Disregard. Must not be a method for that.

**Comment by mackal** [comment]
Doesn't tit play a ping sound for AAs?

**Comment by noudess** [comment]
> Doesn't tit play a ping sound for AAs?

Does it?  I'm on ROF2.  Do I need to make it client based?

**Pull request merged**
