### PR TITLE
[Quest API] Add rule AlternateAugmentationSealer for using a different bagtype

### PR DESCRIPTION
**Pull request by Natedog2012**
…t bagtype as an alternate augmentation sealer. Use EVENT_COMBINE with UseAugmentContainer

Lua Example
```lua
function event_combine(e)
	local bag_id = e.self:GetItemIDAt(e.container_slot)
	if (bag_id == 1267) then
		e.self:UseAugmentContainer(e.container_slot)
		return 1;
	end
end
```

Perl Example
```perl
sub EVENT_COMBINE {
	my $bag_id = $client->GetItemIDAt($container_slot);
	if ($bag_id == 1267) {
		$client->UseAugmentContainer($container_slot); 
		return 1; #We did a custom combine return 1
	}
}
```

### CODE REVIEW

**Comment by Akkadius** [comment]
This isn't a live like feature right? It shouldn't be enabled by default.

**Comment by Akkadius** [comment]
Looks dope though, thanks for taking the time to wrap it up for PRing

**Comment by Natedog2012** [comment]
> This isn't a live like feature right? It shouldn't be enabled by default.

Yeah my bad set it to 53 so its defaulted to just being the BagTypeAugmentationSealer.. so server owners can change it to a different bagtype
https://github.com/EQEmu/Server/blob/master/common/item_data.h#L296

**Comment by Kinglykrab** [comment]
> > This isn't a live like feature right? It shouldn't be enabled by default.
> 
> Yeah my bad set it to 53 so its defaulted to just being the BagTypeAugmentationSealer.. so server owners can change it to a different bagtype https://github.com/EQEmu/Server/blob/master/common/item_data.h#L296

I'd have `-1` be the default and check if value is anything except `-1` for enabled, notes field should say that `-1` means disabled and is default, similar to other stuff recently added.

**Review by Akkadius — APPROVED** [review]
Thanks for making the adjustments. LGTM

**Pull request merged**
