### PR TITLE
[Quest API] Cross zone and world wide method overhaul.

### PR DESCRIPTION
**Pull request by Kinglykrab**
- Adds support for Character ID, Character Name, and Expedition ID to all cross zone methods that did not have a method.
- Adds worldwide LDoN Updates.
- Shrinks the number of packets and structs from 83 to 17.

No quest functionality will be affected by this, as the only changes are the underlying method used to send the cross zone and world wide data.

Note: This is not merge ready and needs to be fully tested as well as combed for issues as there are nearly 200 methods that are part of this.

### CODE REVIEW

**Comment by Kinglykrab** [comment]
- Breaking changes with the following methods
    - quest::crosszonemessageplayerbycharid in Perl.
    - eq.crosszonemessageplayerbycharid in Lua.
    - quest::crosszonemessageplayerbygroupid in Perl.
    - eq.crosszonemessageplayerbyraid in Lua.
    - quest::crosszonemessageplayerbyraidid in Perl.
    - eq.crosszonemessageplayerbygroupid in Lua.
    - quest::crosszonemessageplayerbyguild in Perl.
    - eq.crosszonemessageplayerbyguildid in Lua.
    - quest::crosszonemessageplayerbyname in Perl.
    - eq.crosszonemessageplayerbycharidname in Lua.
- These functions have had their parameters reordered from (type, identifier, message) to (identifier, type, message) to match other cross zone methods.

**Comment by noudess** [comment]
> * Breaking changes with the following methods
>   
>   * quest::crosszonemessageplayerbycharid in Perl.
>   * eq.crosszonemessageplayerbycharid in Lua.
>   * quest::crosszonemessageplayerbygroupid in Perl.
>   * eq.crosszonemessageplayerbyraid in Lua.
>   * quest::crosszonemessageplayerbyraidid in Perl.
>   * eq.crosszonemessageplayerbygroupid in Lua.
>   * quest::crosszonemessageplayerbyguild in Perl.
>   * eq.crosszonemessageplayerbyguildid in Lua.
>   * quest::crosszonemessageplayerbyname in Perl.
>   * eq.crosszonemessageplayerbycharidname in Lua.
> * These functions have had their parameters reordered from (type, identifier, message) to (identifier, type, message) to match other cross zone methods.

Meaning quests will need to be fixed?

**Comment by Kinglykrab** [comment]
> > * Breaking changes with the following methods
> >   
> >   * quest::crosszonemessageplayerbycharid in Perl.
> >   * eq.crosszonemessageplayerbycharid in Lua.
> >   * quest::crosszonemessageplayerbygroupid in Perl.
> >   * eq.crosszonemessageplayerbyraid in Lua.
> >   * quest::crosszonemessageplayerbyraidid in Perl.
> >   * eq.crosszonemessageplayerbygroupid in Lua.
> >   * quest::crosszonemessageplayerbyguild in Perl.
> >   * eq.crosszonemessageplayerbyguildid in Lua.
> >   * quest::crosszonemessageplayerbyname in Perl.
> >   * eq.crosszonemessageplayerbycharidname in Lua.
> > * These functions have had their parameters reordered from (type, identifier, message) to (identifier, type, message) to match other cross zone methods.
> 
> Meaning quests will need to be fixed?

Assuming anyone uses these, sure. They’re not in any standard PEQ quests, so only custom servers making use of them will be affected.

**Comment by noudess** [comment]
> > > * Breaking changes with the following methods
> > >   
> > >   * quest::crosszonemessageplayerbycharid in Perl.
> > >   * eq.crosszonemessageplayerbycharid in Lua.
> > >   * quest::crosszonemessageplayerbygroupid in Perl.
> > >   * eq.crosszonemessageplayerbyraid in Lua.
> > >   * quest::crosszonemessageplayerbyraidid in Perl.
> > >   * eq.crosszonemessageplayerbygroupid in Lua.
> > >   * quest::crosszonemessageplayerbyguild in Perl.
> > >   * eq.crosszonemessageplayerbyguildid in Lua.
> > >   * quest::crosszonemessageplayerbyname in Perl.
> > >   * eq.crosszonemessageplayerbycharidname in Lua.
> > > * These functions have had their parameters reordered from (type, identifier, message) to (identifier, type, message) to match other cross zone methods.
> > 
> > 
> > Meaning quests will need to be fixed?
> 
> Assuming anyone uses these, sure. They’re not in any standard PEQ quests, so only custom servers making use of them will be affected.

Ok thanks.  Im pretty sure I use em, so I'll make sure to fix them once this gets merged.

**Comment by Kinglykrab** [comment]
Tested methods in Perl and Lua. This should be ready for merge.

**Review by Akkadius — APPROVED** [review]
High level looks good to me, haven't had a ton of time to look deeply

Tagging @hgtw to take a look as well

**Review by hgtw — APPROVED** [review]

**Pull request merged**
