### PR TITLE
[Config] Add some missing entries

### PR DESCRIPTION
**Pull request by joligario**

### CODE REVIEW

**Comment by Akkadius** [comment]
I'm not sure how much this config still gets referenced these days. The installer pulls from https://github.com/Akkadius/eqemu-install-v2

**Comment by joligario** [comment]
> 
> 
> I'm not sure how much this config still gets referenced these days. The installer pulls from https://github.com/Akkadius/eqemu-install-v2

Then we should delete these?

**Comment by Akkadius** [comment]
Makes sense to avoid confusion of having multiple sources of truth and things going out dated

**Comment by joligario** [comment]
> 
> 
> Makes sense to avoid confusion of having multiple sources of truth and things going out dated

Only problem is that you can't fill in

**Pull request closed without merging**
