### PR TITLE
[Release] 22.13.1

### PR DESCRIPTION
**Pull request by noudess**
### Targeting

* Revert #3383 ([#3405](https://github.com/EQEmu/Server/pull/3405)) @noudess 2023-06-13

### CODE REVIEW

**Comment by Akkadius** [comment]
Please use the changelog generator tool mentioned in the [release process](https://docs.eqemu.io/developer/release-pipeline/) docs http://spire.akkadius.com/dev/changelog

Note https://github.com/EQEmu/Server/pull/3404 as an example for title, formatting, description

**Comment by noudess** [comment]
> Please use the changelog generator tool mentioned in the [release process](https://docs.eqemu.io/developer/release-pipeline/) docs http://spire.akkadius.com/dev/changelog
> 
> Note #3404 as an example for title, formatting, description

Done, I think.

**Comment by Akkadius** [comment]
Updated your original description, otherwise looks good, thank you for doing that

**Review by Akkadius — APPROVED** [review]

**Comment by Akkadius** [comment]
Updated title to reflect patterns

**Pull request merged**
