### PR TITLE
Enable multiple NPC equipment materials

### PR DESCRIPTION
**Pull request by iequalshane**
This change allows #npcedit
armtexture/bracertexture/handtexture/legtexture/feettexture to work
properly and sets individual armor slot materials for NPCs.

### CODE REVIEW

**Comment by iequalshane** [comment]
Ah, sorry this was missing a header that somehow didn't get added to the commit.

**Comment by KimLS** [comment]
I see changes to database calls but no SQL changes provided?

**Comment by iequalshane** [comment]
This doesn't require an SQL DB change. The current columns for item material work with this change.

**Comment by KimLS** [comment]
Alright thanks for clarifying

**Comment by noudess** [comment]
The fields for the new textures don't exist in my npc_types and I don't see any sql stuff anywhere in the past optional or required that puts them there.  No biggie, I added em manually, but I'm wondering why noone else has an issue?

**Comment by iequalshane** [comment]
Which ones were missing? I used the same existing fields as the #npcedit texture commands (#npcedit armtexture, legtexture, bracertexture, etc)

**Comment by noudess** [comment]
Just zoning in to a zone after server boot.  The npc creation fails do to the npc_types query from the change to  zone/zonedb.cpp.

**Comment by iequalshane** [comment]
I didn't run into this issue when using the DB generated by EQEmu Akka's PEQ Server Repack. I'll investigate tonight when I get home from work.

**Comment by noudess** [comment]
Could just be my db is out of date for that table, but I;ve run the updates from the sql folder.

**Comment by iequalshane** [comment]
Maybe the updates don't add the new entries because they weren't being consume without gm commands before. I'm not too familiar with this area but I wouldn't mind digging into it and resolving this issue so people upgrading older DBs aren't broken.

**Pull request merged**
