### PR TITLE
[Quest API] Add Recipe Methods

### PR DESCRIPTION
**Pull request by Kinglykrab**
- Add $client->GetRecipeMadeCount(recipe_id) to Perl.
- Add $client->HasRecipeLearned(recipe_id) to Perl.
- Add quest::getrecipemadecount(recipe_id) to Perl.
- Add quest::getrecipename(recipe_id) to Perl.
- Add quest::hasrecipelearned(recipe_id) to Perl.
- Add client:GetRecipeMadeCount(recipe_id) to Lua.
- Add client:HasRecipeLearned(recipe_id) to Lua.
- Add eq.get_recipe_made_count(recipe_id) to Lua.
- Add eq.get_recipe_name(recipe_id) to Lua.
- Add eq.has_recipe_learned(recipe_id) to Lua.

### CODE REVIEW

**Review by fryguy503 — APPROVED** [review]
lgtm

**Review by Akkadius — APPROVED** [review]

**Comment by huppyscorner** [comment]
After pulling this update, got all sorts of a errors compiling in debian. Had to revert files back to old, to compile.

**Comment by joligario** [comment]
I've had no issues on debian-based build. Might need more details.

**Comment by huppyscorner** [comment]
The errors were in the zone build, which specified something about recipe's etc. I remember two of the files it referred to, one was lua_client.cpp and perl_client.cpp.

**Pull request merged**
