### PR TITLE
[Quest API] Sit method

### PR DESCRIPTION
**Pull request by GangstaEQ**
See title.

### CODE REVIEW

**Comment by Akkadius** [comment]
This looks fine to me, but we should also add this to Lua

**Review by mackal — CHANGES_REQUESTED** [review]
As Akkadius said, should be exported to lua as well.

**Comment by splose** [comment]
This is actually my code, and unfortunately I don't know how to export it to lua, perhaps one of you can show me?

**Comment by fryguy503** [comment]
> This is actually my code, and unfortunately I don't know how to export it to lua, perhaps one of you can show me?

There are a number of lua implemented snippets here that may be of assistance. https://github.com/EQEmu/Server/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc+lua

**Review by Akkadius — APPROVED** [review]

**Pull request merged**
