### PR TITLE
Improvement of rule descriptions

### PR DESCRIPTION
**Pull request by thalix1337**
Incomplete descriptions added as far as the function was clear to me. Tried to standardize the words used in the descriptions. Corrected a few orthographic problems. Added some words to existing descriptions to make them more understandable. Some rules which were not used anymore are deleted.

### CODE REVIEW

**Comment by Akkadius** [comment]
First; thank you for taking the initiative to make others lives better by adding better descriptions to our rules!

Looks like you were a little liberal on rule removals; there are quite a few errors in the source code compile of rules that were removed that are still being used

https://travis-ci.org/github/EQEmu/Server/builds/700479094#L879

**Comment by freyonsecurity** [comment]
Yes, I still have to work my way in the code. Please don't be annoyed if it takes me a few tries to get the build right. I'll keep at it.

**Comment by thalix1337** [comment]
Yes, I still have to work my way in the code. Please don't be annoyed if it takes me a few tries to get the build right. I'll keep at it.

**Comment by Akkadius** [comment]
Amazing work; looks like we have a few descriptions that need to be filled out yet. Feel free to pull in the devs in coders public to help narrow down getting some of the descriptions filled out so we can get this the rest of the way!

**Comment by thalix1337** [comment]
I have accidentally committed with my business account :-) The Pull Request should now be complete.

**Pull request merged**
