### PR TITLE
Rof merchantlist

### PR DESCRIPTION
**Pull request by clucksoft**
RoF+ can send 200 items to the client at a merchant. I've tested this with RoF, RoF2, and UF.

### CODE REVIEW

**Comment by mackal** [comment]
Are all other clients 80?

**Comment by clucksoft** [comment]
It's been at 80 for all clients in the server code until now. I can't actually verify that Titanium uses 80, but nothing pre-RoF is above 80.

**Comment by clucksoft** [comment]
If any of the other clients use lower than 80, then its been broken for 10 years and I think we'd have reports of missing merchant items on those clients.
Uleat probably knows best when it comes to items: http://www.eqemulator.org/forums/showpost.php?p=231183&postcount=5
His suspicion about merchant list holds true from what I have seen.

**Comment by joligario** [comment]
Titanium doesn't see more than 80 even if you add this change regardless of client.

**Comment by clucksoft** [comment]
Exactly. This is only supposed to allow RoF+ to see more items, since it can.

**Comment by mackal** [comment]
I was more just wondering if all other clients were verified to be 80 or not.

**Comment by joligario** [comment]
You won't need the version bit check. It didn't crash Titanium or UF.

**Comment by clucksoft** [comment]
Yeah, that is true that it doesn't crash UF if you send it more items than it accepts, but I think you may as well cut it short instead of continuing to send items when you know it won't use them.

**Comment by joligario** [comment]
Good point, thanks!

**Pull request merged**
