### PR TITLE
Fishing update to match live 2018 patch

### PR DESCRIPTION
**Pull request by noudess**
From July 28th, 2018 patch:

**- Changed a number of fishing pole items to be unbreakable. Fishing poles that have a chance to break while fishing now display the Expendable flag when inspected.**

From EQTrader's research:

http://mboards.eqtraders.com/eq/forum/tradeskills/fishing/368408-unbreakable-fishing-poles

My own research.  I was able to learn that only poles tagged as magic were unbreakable.

I could have coded this, using the magic flag, but that would not have resulted in the "Expendable" tag on the item.  This is a capture from live this week on a breakable pole:

image

As such, I found the only way I could get this tag, in lower case, like live. was to set the expendablearrow field in items.  Perhaps the field should get a name change, but I didn't want to break anything else.

This is working and tested on my server. 

Re: the sql, I played with updates using item type and item name instead of using specific ids.  However too many exceptions existed, like a pail that is tagged as 36 and poles not called poles, etc.

This sql should keep all standard poles breakable.

### CODE REVIEW

**Comment by mackal** [comment]
I don't think this is the expendable arrow flag controlling this

**Comment by noudess** [comment]
> I don't think this is the expendable arrow flag controlling this

Well, setting it makes our server display the correct graphic.  If you can find another field, tell me and I'll fix it.  It works perfectly.

**Comment by mackal** [comment]
Need to sit down and see if it is in the clients ... Might not be, if it isn't, we can hack the client to show anyways, but server side we should figure out whatever this unknown30 should be called and use that instead of hacking server side to use the arrow flag

**Comment by noudess** [comment]
> Need to sit down and see if it is in the clients ... Might not be, if it isn't, we can hack the client to show anyways, but server side we should figure out whatever this unknown30 should be called and use that instead of hacking server side to use the arrow flag

I agree, but we don't have an unknown30.  So is it a new field we need to add?

**Comment by noudess** [comment]
Modified but not complete.  On hold while @mackal adds support to patchers and items.

**Comment by Akkadius** [comment]
What is still pending with this

**Comment by mackal** [comment]
We need to fully implement SubType for items.

**Comment by noudess** [comment]
I can try this coming week, but was daunted when I first looked at loading a new column into items code.

**Comment by Akkadius** [comment]
New column merged; nice collab guys; awaiting changes post new field

**Comment by noudess** [comment]
Closing this.  Cleaner to open a new one based on current mainline.

**Pull request closed without merging**
