### PR TITLE
[Fixes] AA System Fixes

### PR DESCRIPTION
**Pull request by KimLS**
WIP AA system improvements.

- AA expansion flag behavior is a bit more consistent with how you'd expect it to work.
- AAs will always be loaded even if the expansion is "wrong", this allows refund AA to work more consistently when expansion is changed.
- #reload aa command now will reload the AAs on existing clients.
- Initial implementation of an auto grant system.

### CODE REVIEW

**Comment by Kinglykrab** [comment]
Looking at this made me curious about adding a `MaxAAs()` method to client, so I wrote one up. Only issue is that it's incredibly unoptimized and takes quite a while to finish adding AAs, not sure if there's a better way to do it or not. It basically emulates your auto grant stuff here, minus the expansion specificity. Makes me think if people have all AAs auto grant it could be just as slow though.
```cpp
void Client::MaxAAs()
{
	for (auto& i : zone->aa_abilities) {
		auto ability = i.second.get();

		if (ability->grant_only) {
			continue;
		}

		if (ability->charges > 0) {
			continue;
		}

		auto level = GetLevel();
		auto p     = 1;
		auto r  = ability->first;
		while (r) {
			if (CanUseAlternateAdvancementRank(r)) {
				if (
					r->level_req <= level &&
					!HasAlreadyPurchasedRank(r)
				) {
					FinishAlternateAdvancementPurchase(r, true);
				}
			}
			else {
				break;
			}

			p++;
			r = r->next;
		}
	}
}
```

**Comment by Kinglykrab** [comment]
The above method can actually disconnect the player due to how long it takes and how many messages it sends to client at once. Not sure a way to do it better though.

**Comment by KimLS** [comment]
The best way to do it would probably to add them all in the background without messages.  Later send the AA stats after adding them all.

It's probably the way I should do auto-grant too but I haven't gotten to it yet.

**Comment by Kinglykrab** [comment]
Makes sense to me.

**Comment by KimLS** [comment]
Stole your idea and put it into a command #grantaa

**Comment by KimLS** [comment]
Also took out all the messages so it wont disconnect you.

**Comment by Kinglykrab** [comment]
> Also took out all the messages so it wont disconnect you.

I tested without messages and can still get disconnected if I’m auto granting **all** AAs up to level 70 or something.

**Comment by KimLS** [comment]
I left the messages in for auto-grant for now because the feedback was important but I'm thinking if there's a better way to convey it without so many of them.

**Comment by Kinglykrab** [comment]
I think one of the reason why it crashes is because we're calling `SaveAA()` possibly thousands of times as well as `SendAlternateAdvancementPoints()`, and `SendAlternateAdvancementStats()`. Maybe we should put these behind a bool and just do one update and save at the end of the auto grant?

**Comment by Kinglykrab** [comment]
Can make it nearly instantaneous with this.
```cpp
void Client::MaxAAs()
{
	for (auto& i : zone->aa_abilities) {
		auto ability = i.second.get();

		if (ability->grant_only) {
			continue;
		}

		if (ability->charges > 0) {
			continue;
		}

		auto level = GetLevel();
		auto p     = 1;
		auto r  = ability->first;
		while (r) {
			if (CanUseAlternateAdvancementRank(r)) {
				if (
					r->level_req <= level &&
					!HasAlreadyPurchasedRank(r)
				) {
					FinishAlternateAdvancementPurchase(r, true, false);
				}
			}
			else {
				break;
			}

			p++;
			r = r->next;
		}
	}

	SaveAA();
	SendAlternateAdvancementPoints();
	SendAlternateAdvancementStats();
}
```

```cpp
void Client::FinishAlternateAdvancementPurchase(AA::Rank *rank, bool ignore_cost, bool send_message_and_save) {
	auto rank_id = rank->base_ability->first_rank_id;

	if (rank->base_ability->charges) {
		uint32 charges = 0;
		GetAA(rank_id, &charges);

		if (charges) {
			return;
		}

		SetAA(rank_id, rank->current_value, rank->base_ability->charges);
	} else {
		SetAA(rank_id, rank->current_value, 0);

		//if not max then send next aa
		if (rank->next) {
			SendAlternateAdvancementRank(rank->base_ability->id, rank->next->current_value);
		}
	}

	auto cost = !ignore_cost ? rank->cost : 0;

	m_pp.aapoints -= static_cast<uint32>(cost);

	if (send_message_and_save) {
		SaveAA();
		SendAlternateAdvancementPoints();
		SendAlternateAdvancementStats();
	}

	if (player_event_logs.IsEventEnabled(PlayerEvent::AA_PURCHASE)) {
		auto e = PlayerEvent::AAPurchasedEvent{
			.aa_id = rank->id,
			.aa_cost = cost,
			.aa_previous_id = rank->prev_id,
			.aa_next_id = rank->next_id
		};

		RecordPlayerEventLog(PlayerEvent::AA_PURCHASE, e);
	}

	if (rank->prev) {
		if (send_message_and_save) {
			MessageString(
				Chat::Yellow,
				AA_IMPROVE,
				std::to_string(rank->title_sid).c_str(),
				std::to_string(rank->prev->current_value).c_str(),
				std::to_string(cost).c_str(),
				cost == 1 ? std::to_string(AA_POINT).c_str() : std::to_string(AA_POINTS).c_str()
			);
		}

		/* QS: Player_Log_AA_Purchases */
		if (RuleB(QueryServ, PlayerLogAAPurchases)) {
			const auto event_desc = fmt::format(
				"Ranked AA Purchase :: aa_id:{} at cost:{} in zoneid:{} instid:{}",
				rank->id,
				cost,
				GetZoneID(),
				GetInstanceID()
			);

			QServ->PlayerLogEvent(Player_Log_AA_Purchases, CharacterID(), event_desc);
		}
	} else {
		if (send_message_and_save) {
			MessageString(
				Chat::Yellow,
				AA_GAIN_ABILITY,
				std::to_string(rank->title_sid).c_str(),
				std::to_string(cost).c_str(),
				cost == 1 ? std::to_string(AA_POINT).c_str() : std::to_string(AA_POINTS).c_str()
			);
		}

		/* QS: Player_Log_AA_Purchases */
		if (RuleB(QueryServ, PlayerLogAAPurchases)) {
			const auto event_desc = fmt::format(
				"Initial AA Purchase :: aa_id:{} at cost:{} in zoneid:{} instid:{}",
				rank->id,
				cost,
				GetZoneID(),
				GetInstanceID()
			);

			QServ->PlayerLogEvent(Player_Log_AA_Purchases, CharacterID(), event_desc);
		}
	}

	if (parse->PlayerHasQuestSub(EVENT_AA_BUY)) {
		const auto& export_string = fmt::format(
			"{} {} {} {}",
			cost,
			rank->id,
			rank->prev_id,
			rank->next_id
		);

		parse->EventPlayer(EVENT_AA_BUY, this, export_string, 0);
	}

	CalcBonuses();

	if (cost) {
		if (title_manager.IsNewAATitleAvailable(m_pp.aapoints_spent, GetBaseClass())) {
			NotifyNewTitlesAvailable();
		}
	}
}
```

**Comment by KimLS** [comment]
Will look at changing that.  Was busy / lazy this weekend so didn't touch this.

**Comment by Akkadius** [comment]
Woah, this looks fancy

**Comment by KimLS** [comment]
Updated with Kingly's suggestions for FinishAlternateAdvancementPurchase

**Comment by KimLS** [comment]
Will try to finalize this, this weekend.

**Review by Akkadius — APPROVED** [review]
Nice work on this!

**Pull request merged**
