### PR TITLE
[Expansion] Content Filtering Adjustments

### PR DESCRIPTION
**Pull request by Akkadius**
**Changes**

* Added content filter columns to `spawnentry` to be able to filter at the entry level (min_expansion, max_expansion, content_flags, content_flags_disabled)
* Set all defaults for `min_expansion` and `max_expansion` to `-1` versus the previous default of `0` (Context set below)
* Content flags now properly in inverse case where something is disabled when a flag is disabled. This was not working properly at all before (it is now)
* Also added support for `content_flags` and `content_flags_disabled` to also be able to be empty ('') not just strictly NULL so users don't make mistakes

**Fabled Filtering Example**

Trust originally tried to implement Fabled using the content flags; because the inverse logic was not properly working we could get a fabled to spawn but we couldn't get the non-fabled to spawn when the fabled flag was disabled.

**Setup**

```
MariaDB [peq]> select * from content_flags;
+----+---------------+---------+-------+
| id | flag_name     | enabled | notes |
+----+---------------+---------+-------+
|  1 | peq_halloween |       1 |       |
|  2 | fabled        |       1 |       |
+----+---------------+---------+-------+
2 rows in set (0.000 sec)
```

Example spawnentry

```
MariaDB [peq]> select * from spawnentry where spawngroupID = 11765;
+--------------+-------+--------+------------------------+---------------+---------------+---------------+------------------------+
| spawngroupID | npcID | chance | condition_value_filter | min_expansion | max_expansion | content_flags | content_flags_disabled |
+--------------+-------+--------+------------------------+---------------+---------------+---------------+------------------------+
|        11765 | 89154 |    100 |                      1 |            -1 |            -1 |               | fabled                 |
|        11765 | 89196 |    100 |                      1 |            -1 |            -1 | fabled        | NULL                   |
+--------------+-------+--------+------------------------+---------------+---------------+---------------+------------------------+
2 rows in set (0.000 sec)
```

(Fabled) Enabled

image

(Fabled) Disabled

image

**Expansion Filtering Defaults**

While expansion filtering works great in most cases; 0 as a default value collides with `Classic` and while you shouldn't need to filter on classic in most cases there are still cases where its warranted.

This is primarily a database migration change to shift the default value of `min_expansion` and `max_expansion` to `-1` which is equivalent to **ALL**

```cpp
	enum ExpansionNumber {
		Classic = 0,
		TheRuinsOfKunark,
		TheScarsOfVelious,
		TheShadowsOfLuclin,
// ... truncated
	};
```

### CODE REVIEW

**Comment by joligario** [comment]
>     * Also added support for `content_flags` and `content_flags_disabled` to also be able to be empty ('') not just strictly NULL so users don't make mistakes
/flips table

**Review by Kinglykrab — APPROVED** [review]

**Comment by Akkadius** [comment]
> > ```
> > * Also added support for `content_flags` and `content_flags_disabled` to also be able to be empty ('') not just strictly NULL so users don't make mistakes
> > ```
> 
> /flips table

Your welcome? Lol

**Comment by joligario** [comment]
> > > ```
> > > * Also added support for `content_flags` and `content_flags_disabled` to also be able to be empty ('') not just strictly NULL so users don't make mistakes
> > > ```
> > 
> > 
> > /flips table
> 
> You're welcome? Lol

Was just messing. The amount of trouble it caused at the beginning and the effort to put NULLs into the editor was just a pain.

**Comment by Akkadius** [comment]
> > > > ```
> > > > * Also added support for `content_flags` and `content_flags_disabled` to also be able to be empty ('') not just strictly NULL so users don't make mistakes
> > > > ```
> > > 
> > > 
> > > /flips table
> > 
> > 
> > You're welcome? Lol
> 
> Was just messing. The amount of trouble it caused at the beginning and the effort to put NULLs into the editor was just a pain.

Ah yeah. My apologies. You down for adding `spawnentry` support? :smile:

**Comment by joligario** [comment]
> > > > > ```
> > > > > * Also added support for `content_flags` and `content_flags_disabled` to also be able to be empty ('') not just strictly NULL so users don't make mistakes
> > > > > ```
> > > > 
> > > > 
> > > > /flips table
> > > 
> > > 
> > > You're welcome? Lol
> > 
> > 
> > Was just messing. The amount of trouble it caused at the beginning and the effort to put NULLs into the editor was just a pain.
> 
> Ah yeah. My apologies. You down for adding `spawnentry` support? 😄

Already adding now.

**Pull request merged**
