### PR TITLE
[Feature] Adjust String-based Rules Length

### PR DESCRIPTION
**Pull request by Kinglykrab**
# Notes
- Add support for string-based rules.

# Images
image

### CODE REVIEW

**Comment by Akkadius** [comment]
Shouldn't merge the PR that depends on this before this is merged to make sure its finalized

**Comment by Akkadius** [comment]
This is dope btw

**Comment by nytmyr** [comment]
I think within this or attached to the zone exemptions PR it should update the rule_values column in the rule_values table to allow more than 30 characters now for strings.

**Comment by Akkadius** [comment]
Rebase

**Review by Akkadius — APPROVED** [review]

**Pull request merged**
