### PR TITLE
[Tasks] Add enabled column

### PR DESCRIPTION
**Pull request by Akkadius**
Adds an enabled column (default enabled) so we can import live task data framing and set them as disabled until fully implemented

### CODE REVIEW

**Review by Kinglykrab — APPROVED** [review]

**Comment by Akkadius** [comment]
This still needs to be tested

**Review by hgtw — APPROVED** [review]

**Comment by Akkadius** [comment]
**Testing**

```
  Zone |    Info    | LoadTasks Loaded [478] Tasks 
  Zone |    Info    | LoadTasks Loaded [2065] Task Activities 
```

**Comment by joligario** [comment]
Need a new repository run?

**Comment by Akkadius** [comment]
> Need a new repository run?

Great catch, I swore I had already ran it and committed it and distinctly remember it - but not here. Pushed up

**Review by joligario — APPROVED** [review]

**Pull request merged**
