### PR TITLE
[Strings] Add more number formatters

### PR DESCRIPTION
**Pull request by Kinglykrab**
# Notes
- Adds `Strings::ToUnsignedInt` for `uint32` support.
- Adds `Strings::ToBigInt` for `int64` support.
- Adds `Strings::ToUnsignedBigInt` for `uint64` support.
- Adds `Strings::ToFloat` for `float` support.
- Replaces all `std::stoi` references with `Strings::ToInt`.
- Replaces all `atoi` references with `Strings::ToInt`.
- Replaces all `std::stoul` references with `Strings::ToUnsignedInt`.
- Replaces all `atoul` references with `Strings::ToUnsignedInt`.
- Replaces all `std::stoll` references with `Strings::ToBigInt`.
- Replaces all `atoll` references with `Strings::ToBigInt`.
- Replaces all `std::stoull` references with `Strings::ToUnsignedBigInt`.
- Replaces all `atoull` references with `Strings::ToUnsignedBigInt`.
- Replaces all `std::stof` references with `Strings::ToFloat`.

### CODE REVIEW

**Comment by Akkadius** [comment]
Looks great, clean. 

Gonna need a rebase and we should at least do some respectable surface level testing

**Comment by Akkadius** [comment]
I'll take a look at this one later

**Comment by Akkadius** [comment]
Looked through this all, fairly straightforward.

Have you tested?

I would like to test it and we should probably get at least one other person to also look at it since this is a large surface area

**Comment by Kinglykrab** [comment]
> Looked through this all, fairly straightforward.
> 
> Have you tested?
> 
> I would like to test it and we should probably get at least one other person to also look at it since this is a large surface area

Yeah, I tested, logged in, ran around, bought items, casted spells, just random stuff since it touches quite a large base.

**Comment by Aeadoin** [comment]
> 

I did some testing this this as well, I'm around this weekend if we merge and there's issues (don't think there will be, but this does cover a large scope)

**Review by Aeadoin — CHANGES_REQUESTED** [review]
Going to run some benchmarking on this

**Comment by Aeadoin** [comment]
**Initial Benchmarking Tests:**

```
 World |    Info    | TestCommand Strings::ToInt                       | [10000000] time [7.1543169] 
 World |    Info    | TestCommand std::atoi                               | [10000000] time [4.4151772] 
 World |    Info    | TestCommand Strings::ToBigInt                  | [10000000] time [7.1321781] 
 World |    Info    | TestCommand std::atoll                              | [10000000] time [4.5348305] 
 World |    Info    | TestCommand Strings::ToUnsignedInt         | [10000000] time [6.7901009] 
 World |    Info    | TestCommand std::stoul                             | [10000000] time [12.9080868] 
 World |    Info    | TestCommand Strings::ToUnsignedBigInt    | [10000000] time [7.6201193] 
 World |    Info    | TestCommand std::stoull                            | [10000000] time [13.2821579] 
 World |    Info    | TestCommand Strings::ToFloat                    | [10000000] time [3.1717946] 
 World |    Info    | TestCommand std::stof                               | [10000000] time [15.5878074] 
 World |    Info    | TestCommand Strings::IsNumber                | [10000000] time [5.2171861] 
 World |    Info    | TestCommand Strings::IsUnsignedNumber  | [10000000] time [5.782057] 
 World |    Info    | TestCommand Strings::IsBigNumber            | [10000000] time [5.2007478] 
 World |    Info    | TestCommand Strings::IsUnsignedBigNumber  | [10000000] time [5.823039] ```

**Comment by Akkadius** [comment]
Worked with @Aeadoin @Kinglykrab 

There was concern that `try / catch` has performance impact implications. This is not a bad call-out, however it entirely depends and this thread does a decent job of explaining https://stackoverflow.com/questions/16784601/does-try-catch-block-decrease-performance 

* Removed `try / catch` for simpler `IsNumber` `IsFloat` validation functions
* Removed any non `IsNumber` variants for use of simply `IsNumber`
* Added unit tests to cover scenarios for `IsNumber` `IsFloat`
* Fixed test suite pipeline to just use `stdout` instead of dumping to a file (which didn't have anything anyways)
* Added CLI command `test:string-benchmark` so we can use this benchmark in later testing

**PR as is (unoptimized, debug)**

image

**PR as is (O1)**

image

**Simplifications to IsNumber / IsFloat**

image

**Test Results**

```
eqemu@15bfea186d05:~/server$ server && ~/code/build/bin/tests
Import |    Info    | LoadPaths server [/home/eqemu/server] 
Import |    Info    | LoadPaths logs path [logs] 
Import |    Info    | LoadPaths lua mods path [] 
Import |    Info    | LoadPaths lua_modules path [quests/lua_modules] 
Import |    Info    | LoadPaths maps path [maps] 
Import |    Info    | LoadPaths patches path [assets/patches] 
Import |    Info    | LoadPaths plugins path [quests/plugins] 
Import |    Info    | LoadPaths quests path [quests] 
Import |    Info    | LoadPaths shared_memory path [shared] 
MemoryMappedFileTest: 2/2, 100% correct in 0.000000 seconds
IPCMutexTest: 4/4, 100% correct in 0.000000 seconds
FixedMemoryHashTest: 12/12, 100% correct in 0.000000 seconds
FixedMemoryVariableHashTest: 8/8, 100% correct in 0.000000 seconds
atoboolTest: 13/13, 100% correct in 0.000000 seconds
hextoi_32_64_Test: 12/12, 100% correct in 0.000000 seconds
StringUtilTest: 7/7, 100% correct in 0.000000 seconds
DataVerificationTest: 4/4, 100% correct in 0.000000 seconds
SkillsUtilsTest: 2/2, 100% correct in 0.000000 seconds
TaskStateTest: 16/16, 100% correct in 0.000000 seconds
Total: 80 tests, 100% correct in 0.000000 seconds
```

**Review by Aeadoin — APPROVED** [review]

**Review by Akkadius — APPROVED** [review]

**Pull request merged**
