### PR TITLE
Fix for experiance loss past certain levels

### PR DESCRIPTION
**Pull request by dencelle**
Max level through experience is 112

### CODE REVIEW

**Comment by mackal** [comment]
Well, if sending this string with the data correctly doesn't work, then maybe we shouldn't support higher levels than we should.

**Comment by dencelle** [comment]
this is kind of future proofing, HoT+ on live were level 90+
currently if you try to level past 86ish you will get reset back to 86 due to a overflow
as for the Message_StringID change, i'm not 100% sure why you'd be mad about changing that...

**Comment by dencelle** [comment]
canceling out, seems more or less i'm getting a huge fu... not sure what person's toe i stepped on but eh... i can easily just keep to my self and keep my contributions private

**Comment by mackal** [comment]
Sorry I have not had the time to sit down and look at the reason for the code change. I just didn't like moving away from using the StringID. The rest of the changes will take much longer to analyze. Sorry no one could accommodate you soon enough.

**Pull request closed without merging**
