### PR TITLE
Add defines (commented) for further known SPAs

### PR DESCRIPTION
**Pull request by mackal**
Added as comments since that appears what we were doing. This just gets
us caught up to dev post.

### CODE REVIEW

**Comment by dencelle** [comment]
idk if these should be added or this function should be added... but this is in eqgame... its all of the hard coded darkness spells 
image

**Comment by mackal** [comment]
> idk if these should be added or this function should be added... but this is in eqgame... its all of the hard coded darkness spells
> image

unrelated to this PR, but yes, we probably should have that function, but probably after someone figures out why we need it :P (and implements the feature that uses it)

**Comment by dencelle** [comment]
Yeah, its not really needed on our end, I more just wanted to mention it
since it is hard coded client values

**Review by fryguy503 — APPROVED** [review]
LGTM

**Pull request merged**
