### PR TITLE
[Bug Fixes] Resolve potential zone crashes.

### PR DESCRIPTION
**Pull request by Aeadoin**
Fixes numerous Zone Crashes that I've seen on KMRA recently where null instance is passed into methods.
[crash_lopingplains_version_0_inst_id_0_port_7043_1953522.log](https://github.com/EQEmu/Server/files/10421140/crash_lopingplains_version_0_inst_id_0_port_7043_1953522.log)
[crash_lopingplains_version_0_inst_id_0_port_7061_684812.log](https://github.com/EQEmu/Server/files/10421141/crash_lopingplains_version_0_inst_id_0_port_7061_684812.log)
[crash_oldfieldofbone_version_0_inst_id_0_port_7033_3364593.log](https://github.com/EQEmu/Server/files/10421142/crash_oldfieldofbone_version_0_inst_id_0_port_7033_3364593.log)

### CODE REVIEW

**Comment by mackal** [comment]
I don't see how these changes should actually be needed. Do you have an example of an actual crash?

**Comment by Aeadoin** [comment]
> I don't see how these changes should actually be needed. Do you have an example of an actual crash?

Yeah, here's some where HasPet() returns true, but GetPet() returns null... causing a crash.

`[12-31-2022 17:26:21] [Zone] [Crash] #2  0x000055d31af5e11c in print_trace () at /home/eqemu/code/common/crash.cpp:180
[12-31-2022 17:26:21] [Zone] [Crash] #3  <signal handler called>
[12-31-2022 17:26:21] [Zone] [Crash] #4  HateList::IsHateListEmpty (this=this@entry=0x6940) at /usr/include/c++/10/bits/stl_list.h:404
[12-31-2022 17:26:21] [Zone] [Crash] #5  0x000055d31ac64089 in Mob::IsEngaged (this=0x0) at /home/eqemu/code/zone/mob.h:727
[12-31-2022 17:26:21] [Zone] [Crash] #6  Mob::WipeHateList (this=0x0) at /home/eqemu/code/zone/mob.cpp:3801
[12-31-2022 17:26:21] [Zone] [Crash] #7  0x000055d31a63f310 in Bot::AI_Process (this=<optimized out>) at /home/eqemu/code/zone/bot.cpp:3624
[12-31-2022 17:26:21] [Zone] [Crash] #8  0x000055d31a63c4b4 in Bot::Process (this=0x55d31cf46bf0) at /home/eqemu/code/zone/bot.cpp:2223`

`[01-14-2023 20:46:55] [Zone] [Crash] #2  0x0000556f9d169c48 in print_trace () at /home/eqemu/code/common/crash.cpp:180
[01-14-2023 20:46:55] [Zone] [Crash] #3  <signal handler called>
[01-14-2023 20:46:55] [Zone] [Crash] #4  0x0000556f9ce74ca7 in Mob::SendHPUpdate (this=0x0, force_update_all=false) at /home/eqemu/code/zone/mob.cpp:1424
[01-14-2023 20:46:55] [Zone] [Crash] #5  0x0000556f9c819722 in Bot::Process (this=0x556fa82e0980) at /home/eqemu/code/zone/bot.cpp:2195
[01-14-2023 20:46:55] [Zone] [Crash] #6  0x0000556f9cb69eec in EntityList::MobProcess (this=this@entry=0x556f9d7f1420 <entity_list>) at /home/eqemu/code/zone/entity.cpp:531`

Per KLS previously "KLS: Changed many instances where HasPet() was being checked to verify that we have a valid pet pointer from GetPet(), GetPet() will be used instead, (it is possible to have a valid pet ID and an invalid GetPet() pointer)"

**Comment by mackal** [comment]
https://github.com/EQEmu/Server/blob/7aa25f17f672bc4db40d11c7e4ffb6dd893e04ec/zone/mob.h#L1055 This code is actually different from what `GetPet()` does, which checks the returned mob's owner ID. I think I would rather just do something like:

```c++
if (HasPet()) {
  auto pet = GetPet();
  if (pet != nullptr) {
    ...
  }
{
```

That or get the owner check into `HasPet()` as well.


`this` can also never be null unless there is some memory corruption or something.

**Comment by Aeadoin** [comment]
> 

I mean, I could just rewrite HasPet() to include the owner check... it practically is the same method at that point except one returns a bool, and the other returns the pointer. (which has very limited scope in these contexts)

**Comment by Aeadoin** [comment]
will open new branch, easier I think

**Comment by Akkadius** [comment]
There's multiple issues I see here.

First of all, @mackal you need to work on giving suggestive feedback rather than just saying something is "wrong" or that "you don't like it". Propose an alternative and clear path that can steer Aeadoin to a desired outcome. It's not helpful when people are trying to contribute and it discourages positive change. This has happened repeatedly over time and while you think others are being mean, you should reconsider how you come off in your tone that upsets others. Just because Linus Torvalds berates contributors doesn't mean it's cool or its effective

You also need to stop just blocking people in the community if you want to continue to be a contributing member and deal with the problems you have with them directly. 

I do agree with Mackal in the sense that these functions smell and there should be some untangling there, although I think it should be careful and more thought out than what is in this PR. Fundamentally the way pets are fetched and managed are gross.

I also agree with Mackal that there are excessive calls to `GetPet` as it is doing expensive operations just to fetch what should be a pointer.

`GetPet` also mutates data instead of just fetching data which subsequent calls in the same area of business logic could rely on.

I'm good with the change proposed in the PR because it's largely bot scoped and it puts it in line with how the rest of the code base interacts with pets. The bot code is really the only code using `HasPet()` in business logic in this manner, the rest of the code is using `GetPet()`

**HasPet**

image

**GetPet**

image

**Comment by Aeadoin** [comment]
> There's multiple issues I see here.
> 
> First of all, @mackal you need to work on giving suggestive feedback rather than just saying something is "wrong" or that "you don't like it". Propose an alternative and clear path that can steer Aeadoin to a desired outcome. It's not helpful when people are trying to contribute and it discourages positive change. This has happened repeatedly over time and while you think others are being mean, you should reconsider how you come off in your tone that upsets others. Just because Linus Torvalds berates contributors doesn't mean it's cool or its effective
> 
> You also need to stop just blocking people in the community if you want to continue to be a contributing member and deal with the problems you have with them directly.
> 
> I do agree with Mackal in the sense that these functions smell and there should be some untangling there, although I think it should be careful and more thought out than what is in this PR. Fundamentally the way pets are fetched and managed are gross.
> 
> I also agree with Mackal that there are excessive calls to `GetPet` as it is doing expensive operations just to fetch what should be a pointer.
> 
> `GetPet` also mutates data instead of just fetching data which subsequent calls in the same area of business logic could rely on.
> 
> I'm good with the change proposed in the PR because it's largely bot scoped and it puts it in line with how the rest of the code base interacts with pets. The bot code is really the only code using `HasPet()` in business logic in this manner, the rest of the code is using `GetPet()`
> 
> **HasPet**
> 
> image
> 
> **GetPet**
> 
> image

Thank you Akk. 

I do agree these functions are probably not optimal... and all I'm trying to do is switch to what I see other code doing which is using GetPet() (which where possible should be assigned to a pointer, as long as scope allows, I do agree) as my primary concern currently are crashes from the Bot code.

I'd obviously love to ensure all the existing code I'm having to work off is 100% effective, but if I rewrote everything I came across in a single PR that "smelled" I'd probably never finish.

**Comment by Aeadoin** [comment]
And thank you Mackal, I know you are trying to be of help... and I do appreciate it.

**Comment by mackal** [comment]
> And thank you Mackal, I know you are trying to be of help... and I do appreciate it.

You're welcome. Do not think I was really doing what I was being accused of ... I asked for crashes, which you provided which caused me to dig into see if there was any reason there should be an issue, which I realized there could be and provided some stylistic suggestions. Don't think I was really being negative or shitting on your changes just because I want to be difficult or anything.

**Pull request closed without merging**
