### PR TITLE
[Quest API] Add secondstotime(duration) to Perl and Lua.

### PR DESCRIPTION
**Pull request by KinglyKrab**
Converts time in seconds to human readable string.

- Add quest::secondstotime(duration) to Perl.
- Add eq.seconds_to_time(duration) to Lua.

### CODE REVIEW

**Review by mackal — APPROVED** [review]

**Review by mackal — APPROVED** [review]

**Comment by Akkadius** [comment]
This is great!

One nit: We should change the method name to `humanizetime` as `converttime` is arbitrary and could have many meanings

Lots of libraries use `humanize` or `humantime` for similar meaning / understanding

https://momentjscom.readthedocs.io/en/latest/moment/08-durations/03-humanize/

https://zetcode.com/php/carbon/

**Comment by splose** [comment]
> This is great!
> 
> 
> 
> One nit: We should change the method name to `humanizetime` as `converttime` is arbitrary and could have many meanings
> 
> 
> 
> Lots of libraries use `humanize` or `humantime` for similar meaning / understanding
> 
> 
> 
> https://momentjscom.readthedocs.io/en/latest/moment/08-durations/03-humanize/
> 
> 
> 
> https://zetcode.com/php/carbon/
> 
> 
> 
> 

oh god. 🙄

**Review by KimLS — APPROVED** [review]

**Comment by splose** [comment]
So like... can we merge this or do I have to do it manually?

**Comment by mackal** [comment]
> So like... can we merge this or do I have to do it manually?

Personally I'm fine with the current name, but no one has commented on what @Akkadius suggested.

**Comment by KinglyKrab** [comment]
Just got back home tonight and had a chance to sit down at my computer again.

I personally think that `converttime` is a easier to remember and easier to search for name than `humanizetime`.

I've asked a couple people their opinion about the name as well and they all agreed they'd search for `time` or `convert` before they'd ever search `humanize` or something similar to that.

So I believe we should merge the pull request as is.

**Pull request merged**
