### PR TITLE
[Cheat Detection] Anti-Cheat reimplementation

### PR DESCRIPTION
**Pull request by dencelle**

### CODE REVIEW

**Comment by splose** [comment]
Might as well just merge this at this point.

He's admitted it was just to get under my (and/or kingly's skin) and has done like 10 PRs for it already. Damage is done either way.

Hope he gets what he was looking for out of this :) 🤏

**Comment by emagi** [comment]
closing a git pull doesn't get rid of the final code in the original pull request...

just do:

git pull origin pull/1397/head:master

**Comment by KinglyKrab** [comment]
> 
> 
> closing a git pull doesn't get rid of the final code in the original pull request...
> 
> just do:
> 
> git pull origin pull/1397/head:master

Wasn't trying to get rid of the code, just make him reopen his original pull request, but he deleted the repository.

This one will be fine.

**Comment by splose** [comment]
Closed -- reopening original PR.

**Pull request closed without merging**
