### PR TITLE
[Bug Fix] restore some messages lost due to dup fix 2 years ago

### PR DESCRIPTION
**Pull request by noudess**
Some messages for spells were not getting sent anymore because of a 2 year old fix for duplicate messages.

Old Fix that fixed dups but lost some messages:  https://github.com/EQEmu/Server/commit/60e194e32bb5af2049ff1900c408fa663e60ffef

This is tested but lets get feedback and let me test for another week.

### CODE REVIEW

**Comment by noudess** [comment]
Updated after finding more duplicates of DD messages cast by NPCs.

**Comment by noudess** [comment]
Lifetap spells cast as spells rather than procs have an issue of (2) xyz Staggers to close clients other than the target.  Lifetap cast as a proc do NOT.  I believe this is a bug in CommonDamage and as such I will address it separately.

**Comment by nytmyr** [comment]
Do you know if this resolves the double messages for Canni for Shaman?
For the casting player it shows the "You body aches as your mind clears. You have taken x points of damage." But then repeats a "Your body aches as your mind clears."
When another casts it you see a double "xxx winces."

**Comment by noudess** [comment]
> Do you know if this resolves the double messages for Canni for Shaman? For the casting player it shows the "Your body aches as your mind clears. You have taken x points of damage." But then repeats a "Your body aches as your mind clears." When another casts it you see a double "xxx winces."

Yes.  This removes the 2nd message.

**Comment by noudess** [comment]
Made alot of progress today.  Lifetap is the really odd duck.  When cast by NPCs it all looked good, but in PVP it was  hosed by my fix.  

We have a new fix for this and tested it about 75%.  Gonna test more tomorrow and push changes.,

**Pull request closed without merging**
