### PR TITLE
Bot Naming - View/Delete Databuckets

### PR DESCRIPTION
**Pull request by prestanneth**
Bots:
^botlist - added "account" option, to quickly check who has what bots 
               - added click to spawn any non spawned "owned" bot
^bottitle "add_new_title" or "-remove"
^botsuffix "add_new_suffix" or "-remove"
^botsurname "add_new_surname" or "-remove"

DataBuckets:
(set to account level 80+ , i use for debugging, maybe useful for others..)
#viewbuckets (filterable on key)
#deletebucket (key) - via hyperlink

### CODE REVIEW

**Comment by Akkadius** [comment]
Nice additions

I would like the bucket command to be combined in to one with arguments separating output / functionality

**Example**

#databuckets search
#databuckets delete

**Comment by mackal** [comment]
This should really be split into multiple PRs so the specific experts can comment/accept each change. (Uleat for bots and Akkadius for databuckets)

**Comment by prestanneth** [comment]
[ updated to # databuckets / sample ] (https://imgur.com/a/ubBHus2)

**Comment by alimalkhalifa** [comment]
Not really my place to say, but would it make sense to have the databuckets and bot naming commits as two different PRs? For revert safety 😂

**Comment by Akkadius** [comment]
I'm good with the databuckets side considering the changes were made, the rest I'll leave up to @Uleat

**Comment by Uleat** [comment]
Yep, looks good!

Closing and merging ~

**Pull request merged**
