### PR TITLE
[Commands] Cleanup #scale Command.

### PR DESCRIPTION
**Pull request by Kinglykrab**
- Cleanup messages and logic.

### CODE REVIEW

**Comment by Akkadius** [comment]
I'll review this later in the week

**Comment by Akkadius** [comment]
I'm not sure why changing the messages is necessary in this command

Originally when I wrote this, it would show what it was doing in each phase (Searching) or (Applying) and also just show one entity per line, now we have two lines per entity and it's harder to read when trying to scan quickly

https://docs.eqemu.io/server/npc/npc-scaling/#name-search

**Before**

image

**After**

image

Otherwise, I don't really have issues with the changes as long as it functionally doesn't break anything and output is back to one line per entity

Functionally it at least appears to look the same

image

**Comment by Kinglykrab** [comment]
I'll change the message back to one line.

**Comment by Kinglykrab** [comment]
Made it back to one line.
image

**Review by Akkadius — APPROVED** [review]

**Pull request merged**
