### PR TITLE
Add Race/Class Name and Bitmask Methods.

### PR DESCRIPTION
**Pull request by KinglyKrab**
Adds GetClassBitmask(), GetClassName(), GetRaceBitmask(), and GetRaceName() to Perl/Lua.

### CODE REVIEW

**Comment by mackal** [comment]
I think you forgot the implementations of the functions added to the Client class.

**Comment by KinglyKrab** [comment]
Forgot to push Lua. Going to modify. Not merge ready.

**Comment by KinglyKrab** [comment]
This is ready for another lookover. Pushed Lua up.

**Comment by mackal** [comment]
Looking over it again, I wonder if we should have GetBaseRaceBitmask and a GetRaceBitmask (so rename current one?)

**Comment by KinglyKrab** [comment]
Well my thought process there was you'd only ever need to get a bitmask for their REAL race, as a bitmask for a non-player race is useless. So using BaseRace there is fine in my opinion.

**Review by mackal — APPROVED** [review]

**Pull request merged**
