### PR TITLE
#ww

### PR DESCRIPTION
**Pull request by splose**
Casts a spell on everyone currently online

### CODE REVIEW

**Comment by mackal** [comment]
ww is a bad name.

**Comment by fryguy503** [comment]
Suggestion: Maybe add it as an argument for #cast - e.g. #cast ##### world

**Comment by splose** [comment]
Changed it up a little bit.. still learning how to use GitHub.

I'm open to suggestions but please try to be more constructive than "bad name". Thanks!

**Comment by Akkadius** [comment]
I'd be fine if there was a command that was #worldwide that ended up having a bunch of sub-commands for GM utilities. It would need to print a help menu to inform the user what is available underneath

Example #worldwide 

* cast <spell>
* moveallplayers <zone>
* etc.

As this PR currently stands, there's merge conflicts that need to be resolved, otherwise thanks for taking the time to contribute

**Comment by splose** [comment]
If you leave it I'll do that will be good practice for me..

Should I keep it all in this PR or open another?

**Comment by Akkadius** [comment]
It would be good for you to figure out how to handle merge conflicts; @KinglyKrab should be able to help you through resolving them

If the merge is too gnarly some people just cut another branch and re-add their changes and re-PR

This should be an easy merge conflict to resolve

**Review by KinglyKrab — APPROVED** [review]
Looks good to me.

**Comment by mackal** [comment]
I would prefer this wasn't merged without addressing the comment I left ...

**Comment by Akkadius** [comment]
@KinglyKrab I would have to echo what @mackal said; I left an open suggestion - we shouldn't push PR's through as it voids the point of the process

**Comment by KinglyKrab** [comment]
We can revert if necessary, he changed the name from #ww to #wwcast and removed the merge conflicts, figured it was good to go.

**Comment by splose** [comment]
I'm a bit confused.

Seems you can't make multiple forks so my understanding was that this needed to be pushed through so I could pull it down again and start working on expanding the command in place of what is currently there. Then when done do another PR. I was under the impression that's the way this process is supposed to work.

@mackal's comment was pretty useless and unhelpful. Even still I did address by changing the name. I addressed @Akkadius' response by fixing the merge conflicts. What else needs to be done?

**Comment by mackal** [comment]
I thought both of my comments were very useful, and one of them you 100% understood. The other one was that the provided spell ID needs verification. I even gave an example of another command that takes a user provided spell ID and we do some checks to make sure it's not garbage.


You need to create multiple branches to address the issue you had with git and PRs. Basically, you fork, create a branch with your changes etc and do the same for other fixes you want to open PRs for. Just leave your master up-to-date with upstream.

**Comment by splose** [comment]
Yeah no. You said "ww is a bad name" then cried it got merged without your consent. Those were your only 2 comments prior to this one. So far you're 0 for 3 on any of your comments being useful.

009bbf93f7c75524ec60200bcbeae504

Since you're nitpicking so hard I decided to do some testing in-game to see if checking if the argument is a number its enough. None of these crashed or had any adverse effects so I think it's all good. You can close this now :)

**Comment by Akkadius** [comment]
@splose you should have thicker skin and take the higher road instead of going on the offense with comments that don’t help anyone

If Mackal’s suggestion wasn’t very helpful, then sure communicate that to him. It doesn’t need to devolve into pathetic garbage; the pull request process is one that requires peer review feedback so that we can collectively increase the quality of what goes into the source that the entire community uses, it doesn’t matter how amazing of a coder you are. Feedback doesn’t and shouldn’t be received in a offensively harsh manner, even if someone isn’t giving you the most constructive or descriptive feedback, you can elicit it from other reviewers

“#ww is a bad name” is a valid concern because I agreed above that its not very descriptive, but I agree with you that it doesn’t help you much in terms of feedback, so let me give more context

https://github.com/EQEmu/Server/pull/1170#issuecomment-753694305

Commands should not be cryptic with acronyms, it should be #worldwide because we have a system that is made to alias commands that feel long to type for this reason

Remember that we have a `command_aliases` table for short command inputs, so that #worldwide could be aliased to #ww or other shorthand’s while keeping the descriptive, readable command

In general, titles, labels, function names should make themselves obvious to the end user. Quite a few people gave the feedback of a different command name so it doesn’t pass the smell test. This is simple feedback and a simple change

You don’t need to revert the PR; thanks for making your PR and making an effort to contribute back to the community, it is appreciated and I’m sure someone will definitely make use of your command - however, please get rid of the bullshit, you’re better than that

**Comment by splose** [comment]
Yeah I'm not seeing it that way. My skin was plenty thick this entire PR until he got up in arms about a comment that he didn't even make not being addressed.

Seems like you're telling me I should've made the entire #worldwide command with all that extra functionality in this PR. Which seems strange because I've watched people complain about multiple changes / functionality not being in seperate PRs. Seems like I wouldn't be able to satisfy everyone either way.

My line of thinking was that this PR had been fulfilled. Which seems to be the case since it doesn't need to be reverted. I was using branches for my changes and it would error out when trying to update master. That's the only reason I wanted this pushed through. So I could update my master and make the command you suggested in place of this one.

Seems like I was right and everyone is huffing and puffing for no reason.

**Comment by Akkadius** [comment]
I think you need to work on receiving feedback, this isn’t a personal thing. This is simple, you’re making it bigger than it really is

My very clear suggestion was a name change so that sub commands can be added later; not now

**Pull request merged**
