### PR TITLE
[Cleanup] Make use of AccountStatus constants wherever status is checked or used.

### PR DESCRIPTION
**Pull request by Kinglykrab**
- Cleanup all instances of SendEmoteMessage.
- Cleanup all instances of SendEmoteMessageRaw.
- Cleanup all instances of MessageStatus.
- Convert Quest API method defaults to use constants.
- Convert commands to use constants.

### CODE REVIEW

**Comment by joligario** [comment]
Seen many with 80 admin to bypass locked, etc.

**Comment by joligario** [comment]
So needed. Great work!

**Comment by Akkadius** [comment]
Let's move `AccountStatus` top level and this looks great! 🚀

**Review by Akkadius — CHANGES_REQUESTED** [review]
Change nesting

**Review by Akkadius — APPROVED** [review]
🔥

**Pull request merged**
