### PR TITLE
[Merchants] Fixes issues with 1 charge items purchased with 0

### PR DESCRIPTION
**Pull request by GangstaEQ**
see title

### CODE REVIEW

**Comment by mackal** [comment]
Hmm, I could see this having lots of unintentional changes, gonna need to investigate more.

**Comment by GangstaEQ** [comment]
> Hmm, I could see this having lots of unintentional changes, gonna need to investigate more.
Haven't seen any drawbacks yet. Seems like a typo in the original code that is corrected here.

**Comment by Akkadius** [comment]
> > Hmm, I could see this having lots of unintentional changes, gonna need to investigate more.
> > Haven't seen any drawbacks yet. Seems like a typo in the original code that is corrected here.

Going to have to echo @mackal on this one; this looks like a relatively harmless change - but we do want to be careful with adjustments like this

What do you mean by "Fixes issues with 1 charge items purchased with 0" - 0 what? What issues?

I do need a bit more help understanding the context of this change

**Comment by GangstaEQ** [comment]
> > > Hmm, I could see this having lots of unintentional changes, gonna need to investigate more. 
> > > Haven't seen any drawbacks yet. Seems like a typo in the original code that is corrected here.
> 
> Going to have to echo @mackal on this one; this looks like a relatively harmless change - but we do want to be careful with adjustments like this
> 
> What do you mean by "Fixes issues with 1 charge items purchased with 0" - 0 what? What issues?
> 
> I do need a bit more help understanding the context of this change

So items being purchased with 1 charge were being bought with 0 charges.

**Review by Akkadius — APPROVED** [review]

**Comment by Akkadius** [comment]
> > > > Hmm, I could see this having lots of unintentional changes, gonna need to investigate more.
> > > > Haven't seen any drawbacks yet. Seems like a typo in the original code that is corrected here.
> > 
> > 
> > Going to have to echo @mackal on this one; this looks like a relatively harmless change - but we do want to be careful with adjustments like this
> > What do you mean by "Fixes issues with 1 charge items purchased with 0" - 0 what? What issues?
> > I do need a bit more help understanding the context of this change
> 
> So items being purchased with 1 charge were being bought with 0 charges.

That makes sense; thanks for the clarification. In that case this should be fine

**Pull request merged**
