### PR TITLE
[FIX] Fix for world crash with over 1500 guilds

### PR DESCRIPTION
**Pull request by neckkola**
There was an existing issue with certain clients (RoF2) if there were more than 1500 guilds.  Once there were 1500 guilds, world would crash within the RoF2 Encode of GuildsList.  This was due to an overrun situation between the creation of the guildslist packet, which had a limit of 1500, and no limit within the encoder.

In repairing this, enhancements were made to allow for more than 1500 guilds, instead of limiting.  Titanium has a 1500 guild limit.  UF and RoF2 appear to have a 50k limit.  Therefore, this fix allows for backwards compatibility between clients.

RoF2 will allow guild creation over the 1500 limit, and send the GuildsList packet correctly.  In this case, Titanium will be limited to the first 1500 guilds.  This will result in Titanium clients not receiving guild details for those over the limit which will cause Titanium clients to potentially show incorrect guild tags, guilds not showing in the /lfg filters, etc.  I believe that this is a reasonable response instead of limiting UF/RoF2 servers to only 1500.

During testing, it was also noticed that when a server had 50k guilds, the logic to LoadGuilds() was slow, taking several minutes to load, process, and create the GuildsList packet.  This fix introduces logic changes to increase performance.  Testing indicates a marked improvement to loading.  Further testing with 15k guilds in the database produced acceptable and playable results.  This may need more work if a server ever gets to 15k guilds.  :-)

Fixes # (issue)
This fixes a reported issue seen on PEQ.

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing
This was tested with ~15k guilds in the database, logging in, showing guild tags, opening /lfg filters to demo the list is being sent correctly.
GuildsList2
GuildsList1
GuildsList3-Titanium

Clients tested: 
Titanium, UF, and RoF2

# Checklist

- [X] I have tested my changes
- [X] I have performed a self-review of my code. Ensuring variables, functions and methods are named in a human-readable way, comments are added only where naming of variables, functions and methods can't give enough context.
- [ ] I have made corresponding changes to the documentation (if applicable, if not delete this line)
- [X] I own the changes of my code and take responsibility for the potential issues that occur

### CODE REVIEW

**Comment by Akkadius** [comment]
Pushed up a change to make sure we safely access the permissions map.

I created 1,500 guilds raw in the guilds table and the code makes assumptions about what other data might be there.

We should code defensively around this. Are there other spots where you anticipate this could be a problem if a guild was created as a row in the database table but other tables don't have data present? Do we need to be initializing anything?

Otherwise, I was able to load in fine after making the changes I pushed up

```
World |   Crash    | print_trace [Thread debugging using libthread_db enabled] 
 World |   Crash    | print_trace Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1". 
 World |   Crash    | print_trace 0x00007e66f714eb57 in __GI___wait4 (pid=48242, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30 
 World |   Crash    | print_trace [Current thread is 1 (Thread 0x7e66f7034100 (LWP 48198))] 
 World |   Crash    | print_trace #0  0x00007e66f714eb57 in __GI___wait4 (pid=48242, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30 
 World |   Crash    | print_trace #1  0x00005a2d5d4cdb7f in print_trace () at /home/eqemu/code/common/crash.cpp:281 
 World |   Crash    | print_trace #2  <signal handler called> 
 World |   Crash    | print_trace #3  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44 
 World |   Crash    | print_trace #4  0x00007e66f7105e8f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78 
 World |   Crash    | print_trace #5  0x00007e66f70b6fb2 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26 
 World |   Crash    | print_trace #6  0x00007e66f70a1472 in __GI_abort () at ./stdlib/abort.c:79 
 World |   Crash    | print_trace #7  0x00007e66f7319919 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6 
 World |   Crash    | print_trace #8  0x00007e66f7324e1a in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6 
 World |   Crash    | print_trace #9  0x00007e66f7324e85 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6 
 World |   Crash    | print_trace #10 0x00007e66f73250d8 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6 
 World |   Crash    | print_trace #11 0x00007e66f7319524 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6 
 World |   Crash    | print_trace #12 0x00005a2d5d407e8e in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign (this=0x5a2d5f6a4958, __str="\001\000\000\000\005\000\000\000`\022u_-Z", '\000' <repeats 19 times>, "`t_-Z\000\000\003\000\000\000\000\000\000\0001-1\000E `guild_id`\001\000\000\000\001\000\000\000\001\000\000\000\340\000\000\000:)\000men\000\000!\000\000\000\000\000\000\000The Crypt of Nadox\000\000\000\000\000\0001\000\000\000\000\000\000\000Natimbi, the Broken Shores\000s to click it!\000\000\000\000\000\000\000Dragon Necropolis\000fault "...) at /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/basic_string.tcc:284 
 World |   Crash    | print_trace #13 0x00005a2d5d55fdfc in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign (__str="\001\000\000\000\005\000\000\000`\022u_-Z", '\000' <repeats 19 times>, "`t_-Z\000\000\003\000\000\000\000\000\000\0001-1\000E `guild_id`\001\000\000\000\001\000\000\000\001\000\000\000\340\000\000\000:)\000men\000\000!\000\000\000\000\000\000\000The Crypt of Nadox\000\000\000\000\000\0001\000\000\000\000\000\000\000Natimbi, the Broken Shores\000s to click it!\000\000\000\000\000\000\000Dragon Necropolis\000fault "..., this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/basic_string.h:1571 
 World |   Crash    | print_trace #14 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator= (__str="\001\000\000\000\005\000\000\000`\022u_-Z", '\000' <repeats 19 times>, "`t_-Z\000\000\003\000\000\000\000\000\000\0001-1\000E `guild_id`\001\000\000\000\001\000\000\000\001\000\000\000\340\000\000\000:)\000men\000\000!\000\000\000\000\000\000\000The Crypt of Nadox\000\000\000\000\000\0001\000\000\000\000\000\000\000Natimbi, the Broken Shores\000s to click it!\000\000\000\000\000\000\000Dragon Necropolis\000fault "..., this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/basic_string.h:805 
 World |   Crash    | print_trace #15 BaseGuildManager::LoadGuilds (this=0x5a2d5d858ba0 <guild_mgr>) at /home/eqemu/code/common/guild_base.cpp:123 
 World |   Crash    | print_trace #16 0x00005a2d5d495dfa in WorldBoot::DatabaseLoadRoutines (argc=<optimized out>, argv=<optimized out>) at /home/eqemu/code/world/world_boot.cpp:295 
 World |   Crash    | print_trace #17 0x00005a2d5d45033c in main (argc=1, argv=0x7ffe452e1838) at /home/eqemu/code/world/main.cpp:171 
 World |   Crash    | print_trace [Inferior 1 (process 48198) detached] 
```

**Comment by Akkadius** [comment]
Also, is there a time bomb present here if you have over 50,000 guilds?

**Comment by neckkola** [comment]
Thanks @Akkadius   

The current system will update the permissions table with defaults if they don't exist, though I did not add that for ranks as it was part of the conversion scripts. Happy to add it as well.  I tried to remove the time bomb potential and added a check in the rof2 encoder to limit to the max. I added client namespace constants so it can be portable to other clients.

**Comment by joligario** [comment]
Not too worried about the 50K timebomb. Started with 55K, but I couldn't get the client to load >20K guilds. Even 10K guilds is somewhat unwieldy. Used 10K as my baseline.

**RoF2**
Takes quite some time to load into game from character select (30-45 seconds), and LFGuild window took about 30 seconds to load this. Zoned around no crashes. Delete/Create guild with no issues.
image


**RoF1**
About the same time to load into game. Not sure we handle guilds right on this client. No results on the LFGuild window. Zoned around no crashes. Delete/Create guild with no issues. Guild display doesn't update correctly on delete, guild name disappears on create. Must close/open guild window to return to "Unknown Guild".
image
image


**UF**
Not sure we handle guilds right on this client. Also shows "Unknown Guild". Guild manager thinks I am an officer, not the leader, so I can't delete the guild. Removed myself, but window remains populated. No LFGuild functionality in this client. Zoned around no crashes.
image
image
image
image


**Titanium**
No issues noted. Also no LFGuild functionality in this client. Zoned around no crashes. Shows Unknown Guild, I assume, because I reset the original guild id when creating guilds above to 10001.
image


Some of the guild window/display issues on the last two clients just need a zone.

**Comment by neckkola** [comment]
@joligario Thank you for running through some tests. The #commands do not send the client packets (if I remember correctly) so it is not surprising the you saw ui issues that a zone would fix. The zone will send all the necessary client packets. 

I don't have RoF1 so that client guild mileage may vary. If I can find it I could do some updates for that client. 

The Unknown Guild tag is the result of the client ID not being in the list. Ti is limited to 1500 so as you suspect an id of 1500+ will result in that. 

Will watch for other items and update accordingly. 

Neck

**Comment by joligario** [comment]
No problem.
RoF1 and 2 should basically have the same functionality on the client side

**Review by Akkadius — APPROVED** [review]

**Pull request merged**
