### PR TITLE
[Quest API] Add EVENT_COMBINE to Perl and Lua.

### PR DESCRIPTION
**Pull request by Kinglykrab**
- Exports $container_slot in Perl.
- Exports e.container_slot in Lua.

Allows you to perform events when clicking combine in a tradeskill container.

### CODE REVIEW

**Comment by mackal** [comment]
Is EVENT_COMBINE_VALIDATE not enough?

**Comment by Kinglykrab** [comment]
> 
> 
> Is EVENT_COMBINE_VALIDATE not enough?

EVENT_COMBINE_VALIDATE is for checking if the zone is proper for recipes, doesn't export container, and requires a recipe ID.

This event will allow scripted tradeskill combines independent of database recipes.

**Comment by mackal** [comment]
> > Is EVENT_COMBINE_VALIDATE not enough?
> 
> EVENT_COMBINE_VALIDATE is for checking if the zone is proper for recipes, doesn't export container, and requires a recipe ID.
> 
> This event will allow scripted tradeskill combines independent of database recipes.

that's true. Just kind of still feels silly since we could implement EVENT_COMBINE_VALIDATE with this :P

**Review by Natedog2012 — APPROVED** [review]

**Comment by Natedog2012** [comment]
> Is EVENT_COMBINE_VALIDATE not enough?

This allows for more versatile functionality, I like it.

**Comment by Akkadius** [comment]
Hey this looks familiar

**Review by Akkadius — APPROVED** [review]

**Pull request merged**
