### PR TITLE
[Bug Fix] Fix Bot Spell Entries IDs Capping at 32,767

### PR DESCRIPTION
**Pull request by Kinglykrab**
# Description
- Spell IDs for bots were limited to `32,767` because the field wasn't `unsigned`.

## Type of change
- [X] Bug fix

# Testing
image

# Checklist
- [X] I have tested my changes
- [X] I have performed a self-review of my code. Ensuring variables, functions and methods are named in a human-readable way, comments are added only where naming of variables, functions and methods can't give enough context.
- [X] I own the changes of my code and take responsibility for the potential issues that occur

### CODE REVIEW

**Review by Akkadius — APPROVED** [review]

**Comment by Akkadius** [comment]
I hope the database migration was tested

**Review by Akkadius — CHANGES_REQUESTED** [review]
Actually this is in the wrong manifest

**Comment by Kinglykrab** [comment]
> Actually this is in the wrong manifest

I’ll give it another run through this afternoon and post screenshots.

**Comment by Kinglykrab** [comment]
Ah yeah I just noticed it’s not in the bot manifest. I’ll fix that this afternoon. Good catch.

**Review by Akkadius — APPROVED** [review]

**Pull request merged**
