### PR TITLE
Fixes Bolt spells from hitting the caster in cases where the target dies or zones

### PR DESCRIPTION
**Pull request by GangstaEQ**
See title.

### CODE REVIEW

**Comment by GangstaEQ** [comment]
So the main thing with this PR for me would be turning this into a spdat method where its IsBoltSpell orrrr doing this check for any detrimental. In what cases should a detrimental spell go through on a target who is no longer in the entity list.

**Comment by GangstaEQ** [comment]
this is broke gotta fix

**Comment by KayenEQ** [comment]
```
		Mob *target = entity_list.GetMob(target_id);
		if (!target) {
			InterruptSpell(spell_id);
			return;
		}
```
Let me review this more closely though since I wrote the bolt code. There is probably a better answer.

**Comment by mackal** [comment]
I feel like this is a pretty poor solution. Should probably be able to prevent the damage much sooner and with less side effects.

**Comment by GangstaEQ** [comment]
> I feel like this is a pretty poor solution. Should probably be able to prevent the damage much sooner and with less side effects.

Got any suggestions? I would rather have a fix or better code instead of "poor implementation" accepting any tips or ideas on how to write this better.

**Comment by KayenEQ** [comment]
This is the appropriate fix. The code was intentionally making it so the caster got nuked if no target. But, there is no actual reason it should be like that given the functionality of that target type. I included the fix in my latest pull request. Thanks GangstaEQ for discovering this bug.

https://github.com/EQEmu/Server/pull/1459/commits/5e049d41e0674674f85ba0d0b8fc8fe403c54ca5

**Pull request closed without merging**
