### PR TITLE
Bug fix/recipes ignore container size

### PR DESCRIPTION
**Pull request by daerath**
#610

### CODE REVIEW

**Comment by mackal** [comment]
database.GetItem() may return a nullptr.

**Comment by daerath** [comment]
Updated.  If a nullptr is returned, the ID provided is logged as an error and the method exits.

**Comment by mackal** [comment]
Hmm, would it be better to default to 10?

**Comment by daerath** [comment]
My only concern about defaulting to 10 when the item ID in the packet cannot be found is that I'm not sure how that could happen short of a hacked packet.  That's based on my (possibly incorrect) assumption that the server sends the item IDs to the client, and then the client sends them back and that's where the data comes from in that method.

So I'm not opposed, but I'm not sure of the data flow in this case.

**Comment by daerath** [comment]
After we spoke, this now defaults to 10 if the container isn't found.

**Comment by mackal** [comment]
@Akkadius can you merge this if the SQL looks good to you?

**Pull request merged**
