### PR TITLE
[Crash] Bugfix for zone crash caused by #flymode -1

### PR DESCRIPTION
**Pull request by thalix1337**
Bugfix for zone crash caused by #flymode when invalid values are passed. Also, when #flymode is typed without parameters, the correct syntax is displayed.

### CODE REVIEW

**Review by KinglyKrab — COMMENTED** [review]
Should just atoi the separator argument and check if >= 0 and <= 5.

**Comment by thalix1337** [comment]
> Should just atoi the separator argument and check if >= 0 and <= 5.

I have tried to find the smallest possible change to fix the issue.

**Comment by mackal** [comment]
> Should just atoi the separator argument and check if >= 0 and <= 5.

I agree with this

> > Should just atoi the separator argument and check if >= 0 and <= 5.
> 
> I have tried to find the smallest possible change to fix the issue.

I think just checking IsNumber, atoi, etc is a cleaner fix. Which is better.

**Comment by KinglyKrab** [comment]
> > Should just atoi the separator argument and check if >= 0 and <= 5.
> 
> I have tried to find the smallest possible change to fix the issue.

```cpp
if (strlen(sep->arg[1]) == 1 && sep.IsNumber(1) && atoi(sep->arg[1]) >= 0 && atoi(sep->arg[1]) <= 5)

**Comment by splose** [comment]
^ is the best way to make that code smaller the original is pretty awful.

**Comment by thalix1337** [comment]
> ^ is the best way to make that code smaller the original is pretty awful.

Understood and changed as requested. The PR is tested on my server and works for me. I still have some questions but I will ask them in Discord.

**Review by KinglyKrab — APPROVED** [review]
Looks good to me. 👍

**Comment by splose** [comment]
> > ^ is the best way to make that code smaller the original is pretty awful.
> 
> Understood and changed as requested. The PR is tested on my server and works for me. I still have some questions but I will ask them in Discord.

Just to be clear I was referring to the code that was there before you touched it was awful.

Looks good tho.

**Review by Akkadius — APPROVED** [review]

**Pull request merged**
