### PR TITLE
[Feature] Exempt a zone from IP-limit checks.

### PR DESCRIPTION
**Pull request by catapultam-habeo**
Allows server operators to select a zone to be skipped for checking IP limits. An example use-case would be to allow the Bazaar to be populated by traders without needing to build a scripted IP-exemption infrastructure.

### CODE REVIEW

**Comment by Kinglykrab** [comment]
I think this would be better served as a column in the `zone` table so this isn’t limited to one zone.

**Comment by catapultam-habeo** [comment]
Alternatively - the rule could be a delimited list.

**Comment by Kinglykrab** [comment]
> Alternatively - the rule could be a delimited list.
> 
> I would argue that rule is a better fit, because all existing data regarding IP limits are rules, and looking for them in one place would be more intuitive.

Adding support for string-based rules now. That way things like a delimited list are possible in rules.

**Comment by Kinglykrab** [comment]
Support added [here](https://github.com/EQEmu/Server/pull/4138).

**Review by Kinglykrab — APPROVED** [review]

**Pull request merged**
