### PR TITLE
[Rule] Classic 2HB Animation

### PR DESCRIPTION
**Pull request by splose**
Adds ability to use the ~~old~~ proper 2HB animation and also allows you to do it on a per-zone basis since its rule-based.

### CODE REVIEW

**Review by KinglyKrab — APPROVED** [review]
<3

**Comment by Akkadius** [comment]
If this is what it should be, should this really be rule based?

Curious what others might know on this animation

**Comment by mackal** [comment]
They changed it on live for some reason. No idea what it's current state is on live, but at some point they used 2H Slashing :|

**Comment by KinglyKrab** [comment]
Live uses 2H Slashing animation now. Used to be 2H piercing animation, which works better for piercing weapons. Just a preference thing and allows old servers to turn off/on the old animation for the plethora of TLP/Classic servers we have. Also it's disabled by default so shouldn't be too big of an issue.

**Comment by Akkadius** [comment]
> Live uses 2H Slashing animation now. Used to be 2H piercing animation, which works better for piercing weapons. Just a preference thing and allows old servers to turn off/on the old animation for the plethora of TLP/Classic servers we have. Also it's disabled by default so shouldn't be too big of an issue.

It's less of it being an issue that its disabled by default and moreso if we can avoid extra knobs and have sane defaults that's the main thing I'm trying to ask at here given Splose's original comment "Adds ability to use the ~~old~~ proper 2HB animation'

Given that what we have currently is live like and this does restore classic functionality it makes sense to have the knob

**Review by Akkadius — APPROVED** [review]

**Pull request merged**
