### PR TITLE
Feature/underworld

### PR DESCRIPTION
**Pull request by mackal**
This is used to handle falling off of airplane and zoning so we don't have to hack around it

### CODE REVIEW

**Comment by mackal** [comment]
This field is responsible for controlling some collision, specifically when running over an edge that would result you going "underground." For example in paineel to fall into the hole.

**Review by joligario — APPROVED** [review]
No obvious issues. Good find!

**Comment by thalic** [comment]
I am not quite sure how to test this?

**Comment by mackal** [comment]
> I am not quite sure how to test this?

You can try airplane, do #depopzone to depop our current work around and run off the edge and see what happens.

**Review by Akkadius — APPROVED** [review]
LGTM

**Pull request merged**
