### PR TITLE
[CPP] Update C++ standard to C++17

### PR DESCRIPTION
**Pull request by mackal**

### CODE REVIEW

**Comment by Akkadius** [comment]
Was this tested with MySQL being touched?

**Review by Akkadius — CHANGES_REQUESTED** [review]
Was this tested with MySQL being touched?

**Comment by mackal** [comment]
> Was this tested with MySQL being touched?

I ran around in game, did combat etc

**Review by Akkadius — APPROVED** [review]
Did some testing of my own and tested code that touches the async scheduler logic

**Review by hgtw — APPROVED** [review]

**Pull request merged**
