### PR TITLE
[Bug] Fix for Group Leader Disband Issue

### PR DESCRIPTION
**Pull request by fryguy503**
Added public/private class for oldleadername so we can save the previous leader name when the entity is destroyed then allow us to transfer leadership.

Adjusted DelmemberOOZ and in zone functions to include removal of the old leader when disbanding.

### CODE REVIEW

**Comment by joligario** [comment]
Nice! Hopefully this fixes #368

**Comment by fryguy503** [comment]
We have been using it for ages, I believe the original base design was from our Mac source which was forked from TAKP 4-5 years ago. We adjusted a few things, but there is still the odd group bug when lots of rapid leave/joins happen and people have to just reform the group.

**Review by Akkadius — COMMENTED** [review]
Please update eqemu_log_aliases to have the Group logging aliases

**Review by mackal — APPROVED** [review]

**Comment by Akkadius** [comment]
@fryguy503 please update the changelog

**Review by Akkadius — APPROVED** [review]

**Pull request merged**
