### PR TITLE
Compile fix on linux

### PR DESCRIPTION
**Pull request by snail23**
Hello, EQEmu is currently not compiling on linux due to a small misuse of if statements in a couple constexpr functions in the glm submodule using C++14 assumptions while the standard is set to C++11. Changing `CXX_STANDARD` to `14` fixes this.

Hardware:
- Raspberry Pi 3B+
- Armv7l native
- Armv6k target

Compiler:
- Clang 10.0 & GCC 10

### CODE REVIEW

**Comment by mackal** [comment]
Shouldn't be necessary, sounds like a bug in GLM honestly. Have you tried updating that? GLM should be written to work with C++98 still after all.

**Comment by snail23** [comment]
Hey, yep this is from a fresh clone off the master branch on a fresh raspbian/debian install and it still has the c++14 logic when running `git pull` on the glm submodule. Fixing the few lines on the GLM side would also be doable but this 1 liner seemed like the best course of action.

**Comment by mackal** [comment]
Well, there is something like 4 release of GLM since we last updated the submodule. Whats the line that fails so I can check if it's been fixed upstream and we can bump the submodule.

**Comment by snail23** [comment]
I think this might actually be some kind of constexpr bug with gcc, changing CXX_STANDARD back to 11 seems to compile just fine but with gcc it throws out this:
```
[ 30%] Building CXX object common/CMakeFiles/common.dir/database_instances.cpp.o
[ 30%] Building CXX object submodules/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/RecastMeshDetail.cpp.o
In file included from /home/pi/s/submodules/glm/glm/ext/vector_bool2.hpp:5,
                 from /home/pi/s/submodules/glm/glm/vec2.hpp:5,
                 from /home/pi/s/common/../zone/position.h:22,
                 from /home/pi/s/common/../zone/zonedb.h:8,
                 from /home/pi/s/common/database_instances.cpp:37:
/home/pi/s/submodules/glm/glm/detail/type_vec2.hpp:90:40: error: ‘constexpr const T& glm::vec<2, T, Q>::operator[](glm::vec<2, T, Q>::length_type) const’ cannot be overloaded with ‘constexpr T& glm::vec<2, T, Q>::operator[](glm::vec<2, T, Q>::length_type) const’
   90 |   GLM_FUNC_DECL GLM_CONSTEXPR T const& operator[](length_type i) const;
      |                                        ^~~~~~~~
/home/pi/s/submodules/glm/glm/detail/type_vec2.hpp:89:34: note: previous declaration ‘constexpr T& glm::vec<2, T, Q>::operator[](glm::vec<2, T, Q>::length_type) const’
   89 |   GLM_FUNC_DECL GLM_CONSTEXPR T& operator[](length_type i);
      |                                  ^~~~~~~~
In file included from /home/pi/s/submodules/glm/glm/detail/type_vec2.hpp:398,
                 from /home/pi/s/submodules/glm/glm/ext/vector_bool2.hpp:5,
                 from /home/pi/s/submodules/glm/glm/vec2.hpp:5,
                 from /home/pi/s/common/../zone/position.h:22,
                 from /home/pi/s/common/../zone/zonedb.h:8,
                 from /home/pi/s/common/database_instances.cpp:37:
/home/pi/s/submodules/glm/glm/detail/type_vec2.inl:118:44: error: no declaration matches ‘constexpr const T& glm::vec<2, T, Q>::operator[](glm::vec<2, T, Q>::length_type) const’
  118 |  GLM_FUNC_QUALIFIER GLM_CONSTEXPR T const& vec<2, T, Q>::operator[](typename vec<2, T, Q>::length_type i) const
      |                                            ^~~~~~~~~~~~
/home/pi/s/submodules/glm/glm/detail/type_vec2.inl:104:39: note: candidate is: ‘constexpr T& glm::vec<2, T, Q>::operator[](glm::vec<2, T, Q>::length_type) const’
  104 |  GLM_FUNC_QUALIFIER GLM_CONSTEXPR T & vec<2, T, Q>::operator[](typename vec<2, T, Q>::length_type i)
      |                                       ^~~~~~~~~~~~
In file included from /home/pi/s/submodules/glm/glm/ext/vector_bool2.hpp:5,
                 from /home/pi/s/submodules/glm/glm/vec2.hpp:5,
                 from /home/pi/s/common/../zone/position.h:22,
                 from /home/pi/s/common/../zone/zonedb.h:8,
                 from /home/pi/s/common/database_instances.cpp:37:
/home/pi/s/submodules/glm/glm/detail/type_vec2.hpp:17:9: note: ‘struct glm::vec<2, T, Q>’ defined here
   17 |  struct vec<2, T, Q>
      |         ^~~~~~~~~~~~
In file included from /home/pi/s/submodules/glm/glm/ext/vector_bool3.hpp:5,
                 from /home/pi/s/submodules/glm/glm/vec3.hpp:5,
                 from /home/pi/s/common/../zone/position.h:23,
                 from /home/pi/s/common/../zone/zonedb.h:8,
                 from /home/pi/s/common/database_instances.cpp:37:
/home/pi/s/submodules/glm/glm/detail/type_vec3.hpp:94:40: error: ‘constexpr const T& glm::vec<3, T, Q>::operator[](glm::vec<3, T, Q>::length_type) const’ cannot be overloaded with ‘constexpr T& glm::vec<3, T, Q>::operator[](glm::vec<3, T, Q>::length_type) const’
   94 |   GLM_FUNC_DECL GLM_CONSTEXPR T const& operator[](length_type i) const;
      |                                        ^~~~~~~~
/home/pi/s/submodules/glm/glm/detail/type_vec3.hpp:93:35: note: previous declaration ‘constexpr T& glm::vec<3, T, Q>::operator[](glm::vec<3, T, Q>::length_type) const’
   93 |   GLM_FUNC_DECL GLM_CONSTEXPR T & operator[](length_type i);
      |                                   ^~~~~~~~
In file included from /home/pi/s/submodules/glm/glm/detail/type_vec3.hpp:431,
                 from /home/pi/s/submodules/glm/glm/ext/vector_bool3.hpp:5,
                 from /home/pi/s/submodules/glm/glm/vec3.hpp:5,
                 from /home/pi/s/common/../zone/position.h:23,
                 from /home/pi/s/common/../zone/zonedb.h:8,
                 from /home/pi/s/common/database_instances.cpp:37:
/home/pi/s/submodules/glm/glm/detail/type_vec3.inl:184:44: error: no declaration matches ‘constexpr const T& glm::vec<3, T, Q>::operator[](glm::vec<3, T, Q>::length_type) const’
  184 |  GLM_FUNC_QUALIFIER GLM_CONSTEXPR T const& vec<3, T, Q>::operator[](typename vec<3, T, Q>::length_type i) const
      |                                            ^~~~~~~~~~~~
/home/pi/s/submodules/glm/glm/detail/type_vec3.inl:168:39: note: candidate is: ‘constexpr T& glm::vec<3, T, Q>::operator[](glm::vec<3, T, Q>::length_type) const’
  168 |  GLM_FUNC_QUALIFIER GLM_CONSTEXPR T & vec<3, T, Q>::operator[](typename vec<3, T, Q>::length_type i)
      |                                       ^~~~~~~~~~~~
In file included from /home/pi/s/submodules/glm/glm/ext/vector_bool3.hpp:5,
                 from /home/pi/s/submodules/glm/glm/vec3.hpp:5,
                 from /home/pi/s/common/../zone/position.h:23,
                 from /home/pi/s/common/../zone/zonedb.h:8,
                 from /home/pi/s/common/database_instances.cpp:37:
/home/pi/s/submodules/glm/glm/detail/type_vec3.hpp:17:9: note: ‘struct glm::vec<3, T, Q>’ defined here
   17 |  struct vec<3, T, Q>
      |         ^~~~~~~~~~~~
In file included from /home/pi/s/submodules/glm/glm/ext/vector_bool4.hpp:5,
                 from /home/pi/s/submodules/glm/glm/vec4.hpp:5,
                 from /home/pi/s/common/../zone/position.h:24,
                 from /home/pi/s/common/../zone/zonedb.h:8,
                 from /home/pi/s/common/database_instances.cpp:37:
/home/pi/s/submodules/glm/glm/detail/type_vec4.hpp:92:40: error: ‘constexpr const T& glm::vec<4, T, Q>::operator[](glm::vec<4, T, Q>::length_type) const’ cannot be overloaded with ‘constexpr T& glm::vec<4, T, Q>::operator[](glm::vec<4, T, Q>::length_type) const’
   92 |   GLM_FUNC_DECL GLM_CONSTEXPR T const& operator[](length_type i) const;
      |                                        ^~~~~~~~
/home/pi/s/submodules/glm/glm/detail/type_vec4.hpp:91:35: note: previous declaration ‘constexpr T& glm::vec<4, T, Q>::operator[](glm::vec<4, T, Q>::length_type) const’
   91 |   GLM_FUNC_DECL GLM_CONSTEXPR T & operator[](length_type i);
      |                                   ^~~~~~~~
In file included from /home/pi/s/submodules/glm/glm/detail/type_vec4.hpp:503,
                 from /home/pi/s/submodules/glm/glm/ext/vector_bool4.hpp:5,
                 from /home/pi/s/submodules/glm/glm/vec4.hpp:5,
                 from /home/pi/s/common/../zone/position.h:24,
                 from /home/pi/s/common/../zone/zonedb.h:8,
                 from /home/pi/s/common/database_instances.cpp:37:
/home/pi/s/submodules/glm/glm/detail/type_vec4.inl:495:44: error: no declaration matches ‘constexpr const T& glm::vec<4, T, Q>::operator[](glm::vec<4, T, Q>::length_type) const’
  495 |  GLM_FUNC_QUALIFIER GLM_CONSTEXPR T const& vec<4, T, Q>::operator[](typename vec<4, T, Q>::length_type i) const
      |                                            ^~~~~~~~~~~~
/home/pi/s/submodules/glm/glm/detail/type_vec4.inl:477:38: note: candidate is: ‘constexpr T& glm::vec<4, T, Q>::operator[](glm::vec<4, T, Q>::length_type) const’
  477 |  GLM_FUNC_QUALIFIER GLM_CONSTEXPR T& vec<4, T, Q>::operator[](typename vec<4, T, Q>::length_type i)
      |                                      ^~~~~~~~~~~~
In file included from /home/pi/s/submodules/glm/glm/ext/vector_bool4.hpp:5,
                 from /home/pi/s/submodules/glm/glm/vec4.hpp:5,
                 from /home/pi/s/common/../zone/position.h:24,
                 from /home/pi/s/common/../zone/zonedb.h:8,
                 from /home/pi/s/common/database_instances.cpp:37:
/home/pi/s/submodules/glm/glm/detail/type_vec4.hpp:17:9: note: ‘struct glm::vec<4, T, Q>’ defined here
   17 |  struct vec<4, T, Q>
      |         ^~~~~~~~~~~~
In file included from /home/pi/s/submodules/glm/glm/exponential.hpp:17,
                 from /home/pi/s/submodules/glm/glm/detail/func_geometric.inl:1,
                 from /home/pi/s/submodules/glm/glm/geometric.hpp:116,
                 from /home/pi/s/common/../zone/position.h:25,
                 from /home/pi/s/common/../zone/zonedb.h:8,
                 from /home/pi/s/common/database_instances.cpp:37:
/home/pi/s/submodules/glm/glm/detail/type_vec1.hpp:91:40: error: ‘constexpr const T& glm::vec<1, T, Q>::operator[](glm::vec<1, T, Q>::length_type) const’ cannot be overloaded with ‘constexpr T& glm::vec<1, T, Q>::operator[](glm::vec<1, T, Q>::length_type) const’
   91 |   GLM_FUNC_DECL GLM_CONSTEXPR T const& operator[](length_type i) const;
      |                                        ^~~~~~~~
/home/pi/s/submodules/glm/glm/detail/type_vec1.hpp:90:35: note: previous declaration ‘constexpr T& glm::vec<1, T, Q>::operator[](glm::vec<1, T, Q>::length_type) const’
   90 |   GLM_FUNC_DECL GLM_CONSTEXPR T & operator[](length_type i);
      |                                   ^~~~~~~~
In file included from /home/pi/s/submodules/glm/glm/detail/type_vec1.hpp:307,
                 from /home/pi/s/submodules/glm/glm/exponential.hpp:17,
                 from /home/pi/s/submodules/glm/glm/detail/func_geometric.inl:1,
                 from /home/pi/s/submodules/glm/glm/geometric.hpp:116,
                 from /home/pi/s/common/../zone/position.h:25,
                 from /home/pi/s/common/../zone/zonedb.h:8,
                 from /home/pi/s/common/database_instances.cpp:37:
/home/pi/s/submodules/glm/glm/detail/type_vec1.inl:71:44: error: no declaration matches ‘constexpr const T& glm::vec<1, T, Q>::operator[](glm::vec<1, T, Q>::length_type) const’
   71 |  GLM_FUNC_QUALIFIER GLM_CONSTEXPR T const& vec<1, T, Q>::operator[](typename vec<1, T, Q>::length_type) const
      |                                            ^~~~~~~~~~~~
/home/pi/s/submodules/glm/glm/detail/type_vec1.inl:65:39: note: candidate is: ‘constexpr T& glm::vec<1, T, Q>::operator[](glm::vec<1, T, Q>::length_type) const’
   65 |  GLM_FUNC_QUALIFIER GLM_CONSTEXPR T & vec<1, T, Q>::operator[](typename vec<1, T, Q>::length_type)
      |                                       ^~~~~~~~~~~~
In file included from /home/pi/s/submodules/glm/glm/exponential.hpp:17,
                 from /home/pi/s/submodules/glm/glm/detail/func_geometric.inl:1,
                 from /home/pi/s/submodules/glm/glm/geometric.hpp:116,
                 from /home/pi/s/common/../zone/position.h:25,
                 from /home/pi/s/common/../zone/zonedb.h:8,
                 from /home/pi/s/common/database_instances.cpp:37:
/home/pi/s/submodules/glm/glm/detail/type_vec1.hpp:17:9: note: ‘struct glm::vec<1, T, Q>’ defined here
   17 |  struct vec<1, T, Q>
      |         ^~~~~~~~~~~~
In file included from /home/pi/s/submodules/glm/glm/common.hpp:532,
                 from /home/pi/s/submodules/glm/glm/detail/func_geometric.inl:2,
                 from /home/pi/s/submodules/glm/glm/geometric.hpp:116,
                 from /home/pi/s/common/../zone/position.h:25,
                 from /home/pi/s/common/../zone/zonedb.h:8,
                 from /home/pi/s/common/database_instances.cpp:37:
/home/pi/s/submodules/glm/glm/detail/func_common.inl: In function ‘constexpr genType glm::abs(genType) [with genType = int]’:
/home/pi/s/submodules/glm/glm/detail/func_common.inl:37:2: error: body of ‘constexpr’ function ‘constexpr genType glm::abs(genType) [with genType = int]’ not a return-statement
   37 |  }
      |  ^
make[2]: *** [common/CMakeFiles/common.dir/build.make:238: common/CMakeFiles/common.dir/database_instances.cpp.o] Error 1
```

**Comment by freyonsecurity** [comment]
GCC 10.2 compiles the code without patch and without problems.

**Comment by snail23** [comment]
Strange, that's the version I'm on as well. Different architecture?

```
$ gcc --version
gcc (Raspbian 10.2.0-9+rpi1) 10.2.0

$ lscpu
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               4
Model name:          Cortex-A53
Stepping:            r0p4
CPU max MHz:         1200.0000
CPU min MHz:         600.0000
BogoMIPS:            76.80
Flags:               half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idi
                     vt vfpd32 lpae evtstrm crc32
```

**Comment by freyonsecurity** [comment]
Ah yes, I use x64.

**Pull request merged**
