### PR TITLE
Win64 eqemu_server.pl

### PR DESCRIPTION
**Pull request by alimalkhalifa**
Changed binaries to x64 and got rid of wget.exe for windows, switched to
native WebClient

Uses zipped binaries at Akkadius/EQEmuInstall until appveyor is sorted

### CODE REVIEW

**Comment by KinglyKrab** [comment]
`"my" variable $fh masks earlier declaration in same scope at eqemu_server_two.pl line 346.
"my" variable $fh masks earlier declaration in same scope at eqemu_server_two.pl line 759.
"my" variable $fh masks earlier declaration in same scope at eqemu_server_two.pl line 799.
"my" variable @lines masks earlier declaration in same scope at eqemu_server_two.pl line 1401.
Name "main::isdst" used only once: possible typo at eqemu_server_two.pl line 49.
Name "main::yday" used only once: possible typo at eqemu_server_two.pl line 49.
Name "main::min" used only once: possible typo at eqemu_server_two.pl line 49.
Name "main::sec" used only once: possible typo at eqemu_server_two.pl line 49.
Name "main::wday" used only once: possible typo at eqemu_server_two.pl line 49.
Name "main::mon" used only once: possible typo at eqemu_server_two.pl line 49.
Name "main::check_connection" used only once: possible typo at eqemu_server_two.pl line 253.
Name "main::hour" used only once: possible typo at eqemu_server_two.pl line 49.
Name "main::year" used only once: possible typo at eqemu_server_two.pl line 49.
Name "main::api_call" used only once: possible typo at eqemu_server_two.pl line 168.
Name "main::mday" used only once: possible typo at eqemu_server_two.pl line 49.
eqemu_server_two.pl syntax OK`
Looks like we're using "my" too much. Also some unused variables in there. $api_call and $check_connection don't seem to be used at all. Not sure what the time variables are intended to be used for.

**Comment by KinglyKrab** [comment]
Looks like we're using "my" too much. Also some unused variables in there. $api_call and $check_connection don't seem to be used at all. Not sure what the time variables are intended to be used for.

**Comment by KinglyKrab** [comment]
Removed all the warnings with this diff: https://www.diffchecker.com/BLlpIjz7

**Comment by Akkadius** [comment]
Will be running through testing on this today

**Pull request merged**
