### PR TITLE
[Feature] Change mana_used to int32, This will allow higher mana costs to function correctly

### PR DESCRIPTION
**Pull request by Aeadoin**
mana_cost already uses Int32
mana_used is already Int32 under other functions - CastSpell

### CODE REVIEW

**Comment by mackal** [comment]
https://github.com/EQEmu/Server/blob/20c639c87271463bd716dc181d353e38f553d404/zone/questmgr.h#L357

Can you nuke this line? It doesn't appear to be called, otherwise I'd ask you to update it.

**Comment by Aeadoin** [comment]
@mackal Done.

**Review by mackal — APPROVED** [review]

**Review by mackal — CHANGES_REQUESTED** [review]
ahh why did you delete mob.cpp :P

**Comment by Aeadoin** [comment]
> ahh why did you delete mob.cpp :P

Sorry, I meant to commit those changes to a new PR, how do I go about fixing?

**Comment by mackal** [comment]
> > ahh why did you delete mob.cpp :P
> 
> Sorry, I meant to commit those changes to a new PR, how do I go about fixing?

`git revert 3db8bf04d13d7263632b06da4f95bacfcfcfd60c` should do it

**Review by mackal — APPROVED** [review]

**Review by Kinglykrab — APPROVED** [review]

**Pull request merged**
