### PR TITLE
Added a rule to disallow click training of tomes and fall back to handins.

### PR DESCRIPTION
**Pull request by noudess**
The default for the rule will be to keep behavior the same for all servers.

Only setting it to true (default is false) will disable click-to-train.

Also, if servers add a MeleeSkillLearn to book to their books Table, whatever text they put there will end up as the Item description:   This addresses an issue I found way back in a 2010 post:

http://www.eqemulator.org/forums/showthread.php?p=264511#post264511

image

### CODE REVIEW

**Comment by mackal** [comment]
This seems good to me.

**Comment by KinglyKrab** [comment]
Looks good. 👍

**Comment by mackal** [comment]
Mercs and Bots still use that ItemEnduranceRegenCap rule ... (they need to be rewritten I guess)

**Comment by noudess** [comment]
> Mercs and Bots (edit: oh, clients too lol, missed that) still use that ItemEnduranceRegenCap rule ... (they need to be rewritten I guess)

I hope you know what's going on there?  I added that rule back - so this would compile?  But I dont know why it was gone in the first place?

Just tell me what to do.

**Pull request merged**
